# Generated by Django 5.2.14 on 2026-06-15 14:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('actions', '0004_remove_legacy_operational_taxonomy_fks'),
        ('establishments', '0019_drop_orphan_legacy_taxonomy_tables'),
        ('signals', '0005_signal_issue_focus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('body', models.TextField(max_length=2000)),
                ('action', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='actions.action')),
                ('author_membership', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comments_authored', to='establishments.establishmentmembership')),
                ('establishment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='establishments.establishment')),
                ('signal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='signals.signal')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CommentMention',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mention_links', to='comments.comment')),
                ('mentioned_membership', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comment_mentions_received', to='establishments.establishmentmembership')),
            ],
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['establishment', 'signal', 'created_at', 'id'], name='comments_co_establi_f00df7_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['establishment', 'action', 'created_at', 'id'], name='comments_co_establi_8fd39c_idx'),
        ),
        migrations.AddConstraint(
            model_name='comment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('action__isnull', True), ('signal__isnull', False)), models.Q(('action__isnull', False), ('signal__isnull', True)), _connector='OR'), name='comment_exactly_one_parent'),
        ),
        migrations.AddConstraint(
            model_name='commentmention',
            constraint=models.UniqueConstraint(fields=('comment', 'mentioned_membership'), name='uniq_comment_mention_membership'),
        ),
    ]
