# Generated by Django 5.2.14 on 2026-07-08 12:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("comments", "0004_comment_action_plan_execution"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="commentmention",
            index=models.Index(
                fields=["mentioned_membership", "comment"],
                name="cmt_mnt_member_comment_idx",
            ),
        ),
    ]
