# Generated by Django 5.2.14 on 2026-06-02 12:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("establishments", "0012_remove_membership_domain"),
        ("observations", "0003_observationprocessing_attempt_count_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Signal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("in_progress", "In progress"),
                            ("resolved", "Resolved"),
                            ("canceled", "Canceled"),
                            ("archived", "Archived"),
                        ],
                        default="open",
                        max_length=20,
                    ),
                ),
                (
                    "urgency",
                    models.CharField(
                        choices=[("normal", "Normal"), ("high", "High")],
                        default="normal",
                        max_length=20,
                    ),
                ),
                ("is_pinned", models.BooleanField(default=False)),
                ("pinned_at", models.DateTimeField(blank=True, null=True)),
                ("title", models.CharField(max_length=200)),
                ("structured_summary", models.TextField(max_length=2000)),
                ("location_text", models.CharField(blank=True, default="", max_length=255)),
                ("last_activity_at", models.DateTimeField()),
                (
                    "establishment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="signals",
                        to="establishments.establishment",
                    ),
                ),
                (
                    "operational_domain",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="signals",
                        to="establishments.operationaldomain",
                    ),
                ),
                (
                    "operational_module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="signals",
                        to="establishments.operationalmodule",
                    ),
                ),
                (
                    "operational_subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="signals",
                        to="establishments.operationalsubject",
                    ),
                ),
                (
                    "operational_unit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="signals",
                        to="establishments.operationalunit",
                    ),
                ),
                (
                    "pinned_by_membership",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pinned_signals",
                        to="establishments.establishmentmembership",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CandidateSignal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(blank=True, default="", max_length=200)),
                ("structured_summary", models.TextField(blank=True, default="", max_length=2000)),
                ("schema_version", models.CharField(blank=True, default="", max_length=80)),
                ("ai_aggregate_hint_signal_id", models.UUIDField(blank=True, null=True)),
                (
                    "outcome",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("created_signal", "Created signal"),
                            ("aggregated_signal", "Aggregated signal"),
                            ("rejected", "Rejected"),
                            ("no_signal_created", "No signal created"),
                        ],
                        default="pending",
                        max_length=32,
                    ),
                ),
                (
                    "establishment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="candidate_signals",
                        to="establishments.establishment",
                    ),
                ),
                (
                    "observation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="candidate_signals",
                        to="observations.observation",
                    ),
                ),
                (
                    "operational_domain",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="candidate_signals",
                        to="establishments.operationaldomain",
                    ),
                ),
                (
                    "operational_module",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="candidate_signals",
                        to="establishments.operationalmodule",
                    ),
                ),
                (
                    "operational_subject",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="candidate_signals",
                        to="establishments.operationalsubject",
                    ),
                ),
                (
                    "operational_unit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="candidate_signals",
                        to="establishments.operationalunit",
                    ),
                ),
                (
                    "result_signal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="source_candidates",
                        to="signals.signal",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SignalSourceObservation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "link_type",
                    models.CharField(
                        choices=[
                            ("created_from", "Created from"),
                            ("aggregated_from", "Aggregated from"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "observation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="linked_signals",
                        to="observations.observation",
                    ),
                ),
                (
                    "signal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="source_observation_links",
                        to="signals.signal",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="signal",
            index=models.Index(
                fields=["establishment", "status", "is_pinned", "urgency", "last_activity_at"],
                name="signal_feed_sort_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="signal",
            index=models.Index(
                fields=["establishment", "operational_subject"], name="signal_est_subject_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="candidatesignal",
            index=models.Index(
                fields=["observation", "outcome"], name="cand_signal_obs_outcome_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="signalsourceobservation",
            index=models.Index(fields=["signal"], name="signal_src_obs_signal_idx"),
        ),
        migrations.AddIndex(
            model_name="signalsourceobservation",
            index=models.Index(fields=["observation"], name="signal_src_obs_obs_idx"),
        ),
        migrations.AddConstraint(
            model_name="signalsourceobservation",
            constraint=models.UniqueConstraint(
                fields=("signal", "observation", "link_type"), name="signal_source_obs_unique_link"
            ),
        ),
    ]
