# Generated by Django 5.2.14 on 2026-06-06 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("establishments", "0014_membership_scope_business_unit"),
        ("signals", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidatesignal",
            name="activity_subject",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="candidate_signals",
                to="establishments.activitysubject",
            ),
        ),
        migrations.AddField(
            model_name="candidatesignal",
            name="affected_business_unit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="affected_candidate_signals",
                to="establishments.businessunit",
            ),
        ),
        migrations.AddField(
            model_name="candidatesignal",
            name="location_text",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="candidatesignal",
            name="responsible_business_unit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="responsible_candidate_signals",
                to="establishments.businessunit",
            ),
        ),
        migrations.AddField(
            model_name="signal",
            name="activity_subject",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="signals",
                to="establishments.activitysubject",
            ),
        ),
        migrations.AddField(
            model_name="signal",
            name="affected_business_unit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="affected_signals",
                to="establishments.businessunit",
            ),
        ),
        migrations.AddField(
            model_name="signal",
            name="responsible_business_unit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="responsible_signals",
                to="establishments.businessunit",
            ),
        ),
        migrations.AddIndex(
            model_name="signal",
            index=models.Index(
                fields=["establishment", "affected_business_unit"],
                name="signal_est_affected_bu_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="signal",
            index=models.Index(
                fields=["establishment", "responsible_business_unit"],
                name="signal_est_responsible_bu_idx",
            ),
        ),
    ]
