# Generated by Django 5.2.14 on 2026-06-07 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establishments', '0015_runtime_vocabulary_business_unit'),
        ('signals', '0002_signal_business_unit_classification'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='signal',
            index=models.Index(fields=['establishment', 'activity_subject'], name='signal_est_act_subject_idx'),
        ),
    ]
