# Generated by Django 5.2.14 on 2026-07-28 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establishments', '0030_seed_onboarding_drafts'),
        ('signals', '0012_remove_candidatesignal_ai_aggregate_hint_signal_id'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='signal',
            name='signal_unique_active_aggregation_key',
        ),
        migrations.AlterField(
            model_name='signal',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('interesting', 'Interesting'), ('in_progress', 'In progress'), ('resolved', 'Resolved'), ('canceled', 'Canceled'), ('archived', 'Archived')], default='open', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='signal',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', frozenset(['in_progress', 'interesting', 'open'])), ('routing_status', 'resolved')), fields=('establishment', 'affected_business_unit', 'responsible_business_unit', 'activity_subject', 'operational_unit', 'issue_focus'), name='signal_unique_active_aggregation_key', nulls_distinct=False),
        ),
    ]
