# Generated by Django 5.2.14 on 2026-07-29 11:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establishments', '0030_seed_onboarding_drafts'),
        ('signals', '0013_signal_interesting_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignalResolutionRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requested_at', models.DateTimeField()),
                ('review_route', models.CharField(choices=[('staff_to_manager', 'Staff to manager'), ('manager_to_director', 'Manager to director')], max_length=32)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('canceled', 'Canceled')], default='pending', max_length=20)),
                ('request_comment', models.TextField(blank=True, default='')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_comment', models.TextField(blank=True, default='')),
                ('canceled_at', models.DateTimeField(blank=True, null=True)),
                ('canceled_reason', models.CharField(blank=True, choices=[('canceled_by_requester', 'Canceled by requester'), ('signal_resolved_elsewhere', 'Signal resolved elsewhere'), ('signal_canceled', 'Signal canceled'), ('signal_marked_interesting', 'Signal marked interesting'), ('action_plan_created', 'Action plan created'), ('signal_no_longer_open', 'Signal no longer open')], default='', max_length=40)),
                ('cancel_comment', models.TextField(blank=True, default='')),
                ('requested_by_membership', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='signal_resolution_requests_created', to='establishments.establishmentmembership')),
                ('reviewed_by_membership', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='signal_resolution_requests_reviewed', to='establishments.establishmentmembership')),
                ('signal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resolution_requests', to='signals.signal')),
            ],
            options={
                'indexes': [models.Index(fields=['signal', 'status'], name='sig_res_req_signal_status_idx'), models.Index(fields=['review_route', 'status'], name='sig_res_req_route_status_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('signal',), name='signal_resolution_req_pending_uniq')],
            },
        ),
    ]
