# Generated by Django 5.2.14 on 2026-05-28 13:39

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establishments', '0002_operational_domains'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationalUnit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=100)),
                ('label', models.CharField(max_length=255)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('template', 'Template'), ('ai_proposed', 'AI Proposed')], default='manual', max_length=20)),
                ('active', models.BooleanField(default=True)),
                ('establishment', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='operational_units', to='establishments.establishment')),
            ],
        ),
        migrations.CreateModel(
            name='RoutingHint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pattern', models.CharField(max_length=255)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('template', 'Template'), ('ai_proposed', 'AI Proposed')], default='manual', max_length=20)),
                ('active', models.BooleanField(default=True)),
                ('establishment', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='routing_hints', to='establishments.establishment')),
                ('suggested_unit', models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routing_hints', to='establishments.operationalunit')),
            ],
        ),
        migrations.CreateModel(
            name='RoutingHintDomain',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('operational_domain', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='routing_hint_links', to='establishments.operationaldomain')),
                ('routing_hint', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='domain_links', to='establishments.routinghint')),
            ],
        ),
        migrations.CreateModel(
            name='RuntimeTag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=100)),
                ('label', models.CharField(max_length=255)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('template', 'Template'), ('ai_proposed', 'AI Proposed')], default='manual', max_length=20)),
                ('active', models.BooleanField(default=True)),
                ('establishment', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='runtime_tags', to='establishments.establishment')),
            ],
        ),
        migrations.CreateModel(
            name='RuntimeTagDomain',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('operational_domain', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='runtime_tag_links', to='establishments.operationaldomain')),
                ('runtime_tag', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='domain_links', to='establishments.runtimetag')),
            ],
        ),
        migrations.CreateModel(
            name='RuntimeVocabulary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('term', models.CharField(max_length=255)),
                ('meaning', models.TextField()),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('template', 'Template'), ('ai_proposed', 'AI Proposed')], default='manual', max_length=20)),
                ('active', models.BooleanField(default=True)),
                ('establishment', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='runtime_vocabulary', to='establishments.establishment')),
                ('mapped_domain', models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='runtime_vocabulary', to='establishments.operationaldomain')),
                ('mapped_unit', models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='runtime_vocabulary', to='establishments.operationalunit')),
            ],
        ),
        migrations.CreateModel(
            name='EstablishmentActivityDescription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField()),
                ('source', models.CharField(choices=[('manual', 'Manual')], default='manual', max_length=20)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('establishment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='activity_description', to='establishments.establishment')),
                ('submitted_by', models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_activity_descriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['submitted_by'], name='activity_desc_submitter_idx')],
            },
        ),
        migrations.CreateModel(
            name='OnboardingSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('started', 'Started'), ('description_submitted', 'Description submitted'), ('configuring_runtime', 'Configuring runtime'), ('proposal_ready', 'Proposal ready'), ('validating_sections', 'Validating sections'), ('ready_for_activation', 'Ready for activation'), ('activated', 'Activated'), ('failed', 'Failed'), ('canceled', 'Canceled')], default='started', max_length=40)),
                ('source_mode', models.CharField(choices=[('manual', 'Manual'), ('template', 'Template'), ('ai', 'AI')], default='manual', max_length=20)),
                ('current_step', models.CharField(blank=True, default='', max_length=80)),
                ('ai_attempts', models.PositiveSmallIntegerField(default=0)),
                ('last_error_code', models.CharField(blank=True, default='', max_length=80)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ready_for_activation_at', models.DateTimeField(blank=True, null=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('canceled_at', models.DateTimeField(blank=True, null=True)),
                ('establishment', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_sessions', to='establishments.establishment')),
                ('organization', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_sessions', to='organizations.organization')),
                ('started_by', models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='started_onboarding_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['establishment'], name='onbrd_session_est_idx'), models.Index(fields=['organization'], name='onbrd_session_org_idx'), models.Index(fields=['started_by'], name='onbrd_session_started_idx'), models.Index(fields=['status'], name='onbrd_session_status_idx'), models.Index(fields=['establishment', 'status'], name='onbrd_session_est_status_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ('started', 'description_submitted', 'configuring_runtime', 'proposal_ready', 'validating_sections', 'ready_for_activation'))), fields=('establishment',), name='onboarding_session_est_nonterminal_uniq')],
            },
        ),
        migrations.CreateModel(
            name='OperationalModule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=100)),
                ('label', models.CharField(max_length=255)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('template', 'Template'), ('ai_proposed', 'AI Proposed')], default='manual', max_length=20)),
                ('active', models.BooleanField(default=True)),
                ('establishment', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='operational_modules', to='establishments.establishment')),
            ],
            options={
                'indexes': [models.Index(fields=['establishment'], name='module_est_idx'), models.Index(fields=['establishment', 'active'], name='module_est_active_idx'), models.Index(fields=['key'], name='module_key_idx')],
                'constraints': [models.UniqueConstraint(fields=('establishment', 'key'), name='op_module_est_key_uniq')],
            },
        ),
        migrations.AddIndex(
            model_name='operationalunit',
            index=models.Index(fields=['establishment'], name='unit_est_idx'),
        ),
        migrations.AddIndex(
            model_name='operationalunit',
            index=models.Index(fields=['establishment', 'active'], name='unit_est_active_idx'),
        ),
        migrations.AddIndex(
            model_name='operationalunit',
            index=models.Index(fields=['key'], name='unit_key_idx'),
        ),
        migrations.AddConstraint(
            model_name='operationalunit',
            constraint=models.UniqueConstraint(fields=('establishment', 'key'), name='op_unit_est_key_uniq'),
        ),
        migrations.AddIndex(
            model_name='routinghint',
            index=models.Index(fields=['establishment'], name='routing_hint_est_idx'),
        ),
        migrations.AddIndex(
            model_name='routinghint',
            index=models.Index(fields=['establishment', 'active'], name='routing_hint_est_active_idx'),
        ),
        migrations.AddIndex(
            model_name='routinghint',
            index=models.Index(fields=['suggested_unit'], name='routing_hint_unit_idx'),
        ),
        migrations.AddConstraint(
            model_name='routinghint',
            constraint=models.UniqueConstraint(fields=('establishment', 'pattern'), name='routing_hint_est_pattern_uniq'),
        ),
        migrations.AddIndex(
            model_name='routinghintdomain',
            index=models.Index(fields=['routing_hint'], name='route_hint_domain_hint_idx'),
        ),
        migrations.AddIndex(
            model_name='routinghintdomain',
            index=models.Index(fields=['operational_domain'], name='route_hint_domain_dom_idx'),
        ),
        migrations.AddConstraint(
            model_name='routinghintdomain',
            constraint=models.UniqueConstraint(fields=('routing_hint', 'operational_domain'), name='routing_hint_domain_uniq'),
        ),
        migrations.AddIndex(
            model_name='runtimetag',
            index=models.Index(fields=['establishment'], name='runtime_tag_est_idx'),
        ),
        migrations.AddIndex(
            model_name='runtimetag',
            index=models.Index(fields=['establishment', 'active'], name='runtime_tag_est_active_idx'),
        ),
        migrations.AddIndex(
            model_name='runtimetag',
            index=models.Index(fields=['key'], name='runtime_tag_key_idx'),
        ),
        migrations.AddConstraint(
            model_name='runtimetag',
            constraint=models.UniqueConstraint(fields=('establishment', 'key'), name='runtime_tag_est_key_uniq'),
        ),
        migrations.AddIndex(
            model_name='runtimetagdomain',
            index=models.Index(fields=['runtime_tag'], name='rt_tag_domain_tag_idx'),
        ),
        migrations.AddIndex(
            model_name='runtimetagdomain',
            index=models.Index(fields=['operational_domain'], name='rt_tag_domain_domain_idx'),
        ),
        migrations.AddConstraint(
            model_name='runtimetagdomain',
            constraint=models.UniqueConstraint(fields=('runtime_tag', 'operational_domain'), name='runtime_tag_domain_uniq'),
        ),
        migrations.AddIndex(
            model_name='runtimevocabulary',
            index=models.Index(fields=['establishment'], name='vocab_est_idx'),
        ),
        migrations.AddIndex(
            model_name='runtimevocabulary',
            index=models.Index(fields=['establishment', 'active'], name='vocab_est_active_idx'),
        ),
        migrations.AddIndex(
            model_name='runtimevocabulary',
            index=models.Index(fields=['term'], name='vocab_term_idx'),
        ),
        migrations.AddIndex(
            model_name='runtimevocabulary',
            index=models.Index(fields=['mapped_domain'], name='vocab_mapped_domain_idx'),
        ),
        migrations.AddIndex(
            model_name='runtimevocabulary',
            index=models.Index(fields=['mapped_unit'], name='vocab_mapped_unit_idx'),
        ),
        migrations.AddConstraint(
            model_name='runtimevocabulary',
            constraint=models.UniqueConstraint(fields=('establishment', 'term'), name='runtime_vocab_est_term_uniq'),
        ),
    ]
