# Generated by Django 5.2.14 on 2026-05-28 15:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("establishments", "0003_operationalunit_routinghint_routinghintdomain_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OnboardingCatalogDomain",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("key", models.CharField(max_length=100, unique=True)),
                ("label", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                ("active", models.BooleanField(default=True)),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "ordering": ["sort_order", "key"],
                "indexes": [
                    models.Index(fields=["active"], name="onbrd_cat_domain_active_idx"),
                    models.Index(
                        fields=["active", "sort_order", "key"], name="onbrd_cat_domain_order_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="OnboardingCatalogModule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("key", models.CharField(max_length=100, unique=True)),
                ("label", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                ("active", models.BooleanField(default=True)),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "ordering": ["sort_order", "key"],
                "indexes": [
                    models.Index(fields=["active"], name="onbrd_cat_module_active_idx"),
                    models.Index(
                        fields=["active", "sort_order", "key"], name="onbrd_cat_module_order_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="OnboardingCatalogUnit",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("key", models.CharField(max_length=100, unique=True)),
                ("label", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                ("active", models.BooleanField(default=True)),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "ordering": ["sort_order", "key"],
                "indexes": [
                    models.Index(fields=["active"], name="onbrd_cat_unit_active_idx"),
                    models.Index(
                        fields=["active", "sort_order", "key"], name="onbrd_cat_unit_order_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="OnboardingProposal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("manual", "Manual"),
                            ("template", "Template"),
                            ("ai_proposed", "AI Proposed"),
                        ],
                        default="manual",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("ready", "Ready"),
                            ("partially_validated", "Partially validated"),
                            ("validated", "Validated"),
                            ("applied", "Applied"),
                            ("rejected", "Rejected"),
                            ("failed", "Failed"),
                        ],
                        default="draft",
                        max_length=40,
                    ),
                ),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("section_validation", models.JSONField(blank=True, default=dict)),
                ("validation_errors", models.JSONField(blank=True, default=list)),
                ("validated_at", models.DateTimeField(blank=True, null=True)),
                ("applied_at", models.DateTimeField(blank=True, null=True)),
                ("last_error_code", models.CharField(blank=True, default="", max_length=80)),
                (
                    "applied_by",
                    models.ForeignKey(
                        blank=True,
                        db_index=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="applied_onboarding_proposals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_index=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_onboarding_proposals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "establishment",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="onboarding_proposals",
                        to="establishments.establishment",
                    ),
                ),
                (
                    "onboarding_session",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="proposals",
                        to="establishments.onboardingsession",
                    ),
                ),
                (
                    "validated_by",
                    models.ForeignKey(
                        blank=True,
                        db_index=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="validated_onboarding_proposals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["onboarding_session"], name="onbrd_prop_session_idx"),
                    models.Index(fields=["establishment"], name="onbrd_prop_est_idx"),
                    models.Index(fields=["status"], name="onbrd_prop_status_idx"),
                    models.Index(fields=["source"], name="onbrd_prop_source_idx"),
                    models.Index(fields=["created_by"], name="onbrd_prop_created_idx"),
                    models.Index(fields=["validated_by"], name="onbrd_prop_validated_idx"),
                    models.Index(fields=["applied_at"], name="onbrd_prop_applied_idx"),
                    models.Index(
                        fields=["onboarding_session", "status"], name="onbrd_prop_sess_status_idx"
                    ),
                    models.Index(
                        fields=["establishment", "status"], name="onbrd_prop_est_status_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(
                            ("status__in", ("draft", "ready", "partially_validated", "validated"))
                        ),
                        fields=("onboarding_session",),
                        name="onbrd_prop_session_open_uniq",
                    )
                ],
            },
        ),
    ]
