# Generated by Django 5.2.14 on 2026-05-28 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establishments', '0005_seed_onboarding_catalogs'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationaldomain',
            name='managed_by_onboarding_proposal',
            field=models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_operational_domains', to='establishments.onboardingproposal'),
        ),
        migrations.AddField(
            model_name='operationalmodule',
            name='managed_by_onboarding_proposal',
            field=models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_operational_modules', to='establishments.onboardingproposal'),
        ),
        migrations.AddField(
            model_name='operationalunit',
            name='managed_by_onboarding_proposal',
            field=models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_operational_units', to='establishments.onboardingproposal'),
        ),
        migrations.AddField(
            model_name='routinghint',
            name='managed_by_onboarding_proposal',
            field=models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_routing_hints', to='establishments.onboardingproposal'),
        ),
        migrations.AddField(
            model_name='runtimetag',
            name='managed_by_onboarding_proposal',
            field=models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_runtime_tags', to='establishments.onboardingproposal'),
        ),
        migrations.AddField(
            model_name='runtimevocabulary',
            name='managed_by_onboarding_proposal',
            field=models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_runtime_vocabulary', to='establishments.onboardingproposal'),
        ),
        migrations.AddIndex(
            model_name='operationaldomain',
            index=models.Index(fields=['managed_by_onboarding_proposal'], name='domain_managed_prop_idx'),
        ),
        migrations.AddIndex(
            model_name='operationalmodule',
            index=models.Index(fields=['managed_by_onboarding_proposal'], name='module_managed_prop_idx'),
        ),
        migrations.AddIndex(
            model_name='operationalunit',
            index=models.Index(fields=['managed_by_onboarding_proposal'], name='unit_managed_prop_idx'),
        ),
        migrations.AddIndex(
            model_name='routinghint',
            index=models.Index(fields=['managed_by_onboarding_proposal'], name='routing_hint_prop_idx'),
        ),
        migrations.AddIndex(
            model_name='runtimetag',
            index=models.Index(fields=['managed_by_onboarding_proposal'], name='runtime_tag_prop_idx'),
        ),
        migrations.AddIndex(
            model_name='runtimevocabulary',
            index=models.Index(fields=['managed_by_onboarding_proposal'], name='vocab_managed_prop_idx'),
        ),
    ]
