# Generated by Django 5.2.14 on 2026-05-31 11:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establishments', '0007_catalog_subjects_and_hierarchy'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='establishmentmembership',
            constraint=models.UniqueConstraint(condition=models.Q(('role', 'director'), ('status__in', ['invited', 'active'])), fields=('establishment',), name='unique_active_or_invited_director_per_establishment'),
        ),
    ]
