# Generated by Django 5.2.14 on 2026-05-31 11:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establishments', '0008_unique_active_or_invited_director_per_establishment'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstablishmentInvitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('token_digest', models.CharField(max_length=64, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('membership', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='establishments.establishmentmembership')),
            ],
            options={
                'indexes': [models.Index(fields=['membership'], name='est_invitation_membership_idx'), models.Index(fields=['expires_at'], name='est_invitation_expires_idx')],
            },
        ),
    ]
