# Generated by Django 5.2.14 on 2026-06-01 13:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("establishments", "0011_backfill_membership_scope_from_domain"),
    ]

    operations = [
        migrations.DeleteModel(
            name="MembershipDomain",
        ),
    ]
