# Generated by Django 5.2.14 on 2026-07-15 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establishments', '0022_catalog_lot1'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitysubject',
            name='routing_key',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='businessunit',
            name='instance_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='businessunit',
            name='normalized_specific_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='businessunit',
            name='routing_key',
            field=models.CharField(blank=True, max_length=180, null=True),
        ),
        migrations.AddField(
            model_name='businessunit',
            name='specific_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='activitysubject',
            name='normalized_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AddConstraint(
            model_name='activitysubject',
            constraint=models.UniqueConstraint(condition=models.Q(('routing_key__isnull', False)), fields=('business_unit', 'routing_key'), name='activity_subject_bu_routing_key_uniq'),
        ),
        migrations.AddConstraint(
            model_name='businessunit',
            constraint=models.UniqueConstraint(condition=models.Q(('normalized_specific_name__isnull', False)), fields=('establishment', 'normalized_specific_name'), name='bu_est_normalized_specific_name_uniq'),
        ),
        migrations.AddConstraint(
            model_name='businessunit',
            constraint=models.UniqueConstraint(condition=models.Q(('routing_key__isnull', False)), fields=('establishment', 'routing_key'), name='bu_est_routing_key_uniq'),
        ),
    ]
