# Generated by Django 5.2.14 on 2026-07-27 15:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establishments', '0028_establishment_org_name_ci_uniq'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OnboardingDraft',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('onboarding_session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='draft', to='establishments.onboardingsession')),
                ('updated_by', models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_onboarding_drafts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['updated_by'], name='onbrd_draft_updated_by_idx')],
            },
        ),
    ]
