# Generated by Django 5.2.14 on 2026-09-10 08:32

import django.db.models.functions.text
import django.db.models.lookups
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establishments', '0032_alter_contentreport_content_kind_and_more'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='establishment',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddConstraint(
            model_name='establishment',
            constraint=models.CheckConstraint(condition=models.Q(('status', 'draft'), models.Q(('name__isnull', False), django.db.models.lookups.GreaterThan(django.db.models.functions.text.Length(django.db.models.functions.text.Trim('name')), 0)), _connector='OR'), name='establishment_non_draft_requires_name'),
        ),
    ]
