# Generated by Django 5.2.14 on 2026-07-30 11:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('establishments', '0030_seed_onboarding_drafts'),
    ]

    operations = [
        migrations.CreateModel(
            name='GamificationSeason',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('timezone', models.CharField(max_length=63)),
                ('rule_version', models.CharField(default='gamification_rules_v1', max_length=64)),
                ('status', models.CharField(choices=[('active', 'Active'), ('closed', 'Closed')], default='active', max_length=16)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('establishment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gamification_seasons', to='establishments.establishment')),
            ],
        ),
        migrations.CreateModel(
            name='BadgeAward',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('badge_code', models.CharField(choices=[('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold')], max_length=16)),
                ('points_total', models.IntegerField()),
                ('awarded_at', models.DateTimeField()),
                ('establishment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badge_awards', to='establishments.establishment')),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='badge_awards', to='establishments.establishmentmembership')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='badge_awards', to='gamification.gamificationseason')),
            ],
        ),
        migrations.CreateModel(
            name='PointTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delta', models.IntegerField()),
                ('reason_code', models.CharField(max_length=64)),
                ('source_type', models.CharField(max_length=64)),
                ('source_id', models.CharField(max_length=64)),
                ('source_event_id', models.CharField(blank=True, default='', max_length=64)),
                ('rule_version', models.CharField(max_length=64)),
                ('occurred_at', models.DateTimeField()),
                ('idempotency_key', models.CharField(max_length=255)),
                ('metadata_safe', models.JSONField(blank=True, default=dict)),
                ('establishment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point_transactions', to='establishments.establishment')),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='point_transactions', to='establishments.establishmentmembership')),
                ('reversed_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversals', to='gamification.pointtransaction')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='point_transactions', to='gamification.gamificationseason')),
            ],
        ),
        migrations.AddIndex(
            model_name='gamificationseason',
            index=models.Index(fields=['establishment', 'status'], name='gamificatio_establi_a71364_idx'),
        ),
        migrations.AddIndex(
            model_name='gamificationseason',
            index=models.Index(fields=['establishment', 'starts_at', 'ends_at'], name='gamificatio_establi_92286a_idx'),
        ),
        migrations.AddConstraint(
            model_name='gamificationseason',
            constraint=models.UniqueConstraint(fields=('establishment', 'starts_at'), name='gamification_season_estab_starts_uniq'),
        ),
        migrations.AddConstraint(
            model_name='gamificationseason',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('establishment',), name='gamification_season_one_active_per_estab'),
        ),
        migrations.AddConstraint(
            model_name='gamificationseason',
            constraint=models.CheckConstraint(condition=models.Q(('starts_at__lt', models.F('ends_at'))), name='gamification_season_starts_before_ends'),
        ),
        migrations.AddConstraint(
            model_name='gamificationseason',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('closed_at__isnull', True), ('status', 'active')), models.Q(('closed_at__isnull', False), ('status', 'closed')), _connector='OR'), name='gamification_season_status_closed_at'),
        ),
        migrations.AddIndex(
            model_name='badgeaward',
            index=models.Index(fields=['establishment', 'season'], name='gamificatio_establi_859567_idx'),
        ),
        migrations.AddConstraint(
            model_name='badgeaward',
            constraint=models.UniqueConstraint(fields=('membership', 'season'), name='gamification_badge_award_membership_season_uniq'),
        ),
        migrations.AddIndex(
            model_name='pointtransaction',
            index=models.Index(fields=['season', 'membership'], name='gamificatio_season__8fc16d_idx'),
        ),
        migrations.AddIndex(
            model_name='pointtransaction',
            index=models.Index(fields=['establishment', 'occurred_at'], name='gamificatio_establi_767369_idx'),
        ),
        migrations.AddConstraint(
            model_name='pointtransaction',
            constraint=models.UniqueConstraint(fields=('idempotency_key',), name='gamification_point_tx_idempotency_uniq'),
        ),
        migrations.AddConstraint(
            model_name='pointtransaction',
            constraint=models.CheckConstraint(condition=models.Q(('delta', 0), _negated=True), name='gamification_point_tx_delta_nonzero'),
        ),
        migrations.AddConstraint(
            model_name='pointtransaction',
            constraint=models.CheckConstraint(condition=models.Q(('idempotency_key', ''), _negated=True), name='gamification_point_tx_idempotency_nonempty'),
        ),
    ]
