# Generated by Django 5.2.14 on 2026-06-29 10:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('establishments', '0020_establishmentmembership_notifications_enabled'),
        ('signals', '0006_signal_unique_active_aggregation_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='', max_length=2000)),
                ('requires_validation', models.BooleanField(default=True)),
                ('is_reusable', models.BooleanField(default=False)),
                ('catalog_status', models.CharField(blank=True, choices=[('active', 'Active'), ('inactive', 'Inactive')], max_length=16, null=True)),
                ('activity_subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='action_plans', to='establishments.activitysubject')),
                ('affected_business_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='affected_action_plans', to='establishments.businessunit')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='action_plans_created', to='establishments.establishmentmembership')),
                ('establishment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_plans', to='establishments.establishment')),
                ('pilot_business_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pilot_action_plans', to='establishments.businessunit')),
                ('responsible_business_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='responsible_action_plans', to='establishments.businessunit')),
            ],
        ),
        migrations.CreateModel(
            name='ActionPlanExecution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='', max_length=2000)),
                ('requires_validation', models.BooleanField(default=True)),
                ('use_shared_chronology', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('in_progress', 'In progress'), ('pending_validation', 'Pending validation'), ('done', 'Done'), ('canceled', 'Canceled')], default='in_progress', max_length=32)),
                ('occurrence_date', models.DateField(blank=True, null=True)),
                ('start_at', models.DateTimeField(blank=True, null=True)),
                ('visible_from', models.DateTimeField(blank=True, null=True)),
                ('end_at', models.DateTimeField(blank=True, null=True)),
                ('last_activity_at', models.DateTimeField()),
                ('marked_done_at', models.DateTimeField(blank=True, null=True)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('canceled_at', models.DateTimeField(blank=True, null=True)),
                ('action_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='executions', to='action_plans.actionplan')),
                ('activity_subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='action_plan_executions', to='establishments.activitysubject')),
                ('affected_business_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='affected_action_plan_executions', to='establishments.businessunit')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='action_plan_executions_created', to='establishments.establishmentmembership')),
                ('establishment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_plan_executions', to='establishments.establishment')),
                ('pilot_business_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pilot_action_plan_executions', to='establishments.businessunit')),
                ('responsible_business_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='responsible_action_plan_executions', to='establishments.businessunit')),
                ('source_signal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='action_plan_executions', to='signals.signal')),
            ],
        ),
        migrations.CreateModel(
            name='ActionPlanExecutionTeam',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_pilot', models.BooleanField(default=False)),
                ('action_plan_execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execution_teams', to='action_plans.actionplanexecution')),
                ('business_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='action_plan_execution_teams', to='establishments.businessunit')),
            ],
        ),
        migrations.CreateModel(
            name='ActionPlanAssignee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_at', models.DateTimeField(blank=True, null=True)),
                ('visible_from', models.DateTimeField(blank=True, null=True)),
                ('end_at', models.DateTimeField(blank=True, null=True)),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='action_plan_execution_assignments', to='establishments.establishmentmembership')),
                ('action_plan_execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignees', to='action_plans.actionplanexecution')),
                ('execution_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignees', to='action_plans.actionplanexecutionteam')),
            ],
        ),
        migrations.CreateModel(
            name='ActionPlanSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('use_shared_chronology', models.BooleanField(default=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('start_at', models.TimeField()),
                ('end_at', models.TimeField()),
                ('recurrence_days', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=16)),
                ('last_materialized_at', models.DateTimeField(blank=True, null=True)),
                ('action_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='action_plans.actionplan')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='action_plan_schedules_created', to='establishments.establishmentmembership')),
                ('establishment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_plan_schedules', to='establishments.establishment')),
            ],
        ),
        migrations.AddField(
            model_name='actionplanexecution',
            name='action_plan_schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='executions', to='action_plans.actionplanschedule'),
        ),
        migrations.CreateModel(
            name='ActionPlanScheduleAssignee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_at', models.TimeField(blank=True, null=True)),
                ('end_at', models.TimeField(blank=True, null=True)),
                ('action_plan_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_assignees', to='action_plans.actionplanschedule')),
                ('business_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='action_plan_schedule_assignees', to='establishments.businessunit')),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='action_plan_schedule_assignments', to='establishments.establishmentmembership')),
            ],
        ),
        migrations.CreateModel(
            name='ActionPlanTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('task', models.CharField(max_length=500)),
                ('position', models.PositiveIntegerField()),
                ('action_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='action_plans.actionplan')),
                ('business_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='action_plan_tasks', to='establishments.businessunit')),
            ],
            options={
                'ordering': ['position', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ActionPlanExecutionTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('task', models.CharField(max_length=500)),
                ('position', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('done', 'Done'), ('skipped', 'Skipped'), ('observation_created', 'Observation created')], default='pending', max_length=32)),
                ('skipped_reason', models.CharField(blank=True, max_length=500, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('skipped_at', models.DateTimeField(blank=True, null=True)),
                ('observation_created_at', models.DateTimeField(blank=True, null=True)),
                ('action_plan_execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_executions', to='action_plans.actionplanexecution')),
                ('execution_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_executions', to='action_plans.actionplanexecutionteam')),
                ('action_plan_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='execution_tasks', to='action_plans.actionplantask')),
            ],
            options={
                'ordering': ['position', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='actionplan',
            index=models.Index(fields=['establishment', 'pilot_business_unit', 'catalog_status'], name='ap_plan_catalog_idx'),
        ),
        migrations.AddIndex(
            model_name='actionplan',
            index=models.Index(fields=['establishment', 'created_by'], name='ap_plan_est_creator_idx'),
        ),
        migrations.AddConstraint(
            model_name='actionplan',
            constraint=models.CheckConstraint(condition=models.Q(('pilot_business_unit__isnull', False)), name='action_plan_pilot_business_unit_required'),
        ),
        migrations.AddConstraint(
            model_name='actionplan',
            constraint=models.CheckConstraint(condition=models.Q(('catalog_status__isnull', True), ('is_reusable', True), _negated=True), name='action_plan_reusable_requires_catalog_status'),
        ),
        migrations.AddConstraint(
            model_name='actionplan',
            constraint=models.CheckConstraint(condition=models.Q(('catalog_status__isnull', False), ('is_reusable', False), _negated=True), name='action_plan_non_reusable_null_catalog_status'),
        ),
        migrations.AddConstraint(
            model_name='actionplanexecutionteam',
            constraint=models.UniqueConstraint(fields=('action_plan_execution', 'business_unit'), name='uniq_action_plan_execution_team_business_unit'),
        ),
        migrations.AddConstraint(
            model_name='actionplanexecutionteam',
            constraint=models.UniqueConstraint(condition=models.Q(('is_pilot', True)), fields=('action_plan_execution',), name='uniq_action_plan_execution_team_pilot'),
        ),
        migrations.AddConstraint(
            model_name='actionplanassignee',
            constraint=models.UniqueConstraint(fields=('action_plan_execution', 'membership'), name='uniq_action_plan_execution_assignee'),
        ),
        migrations.AddIndex(
            model_name='actionplanschedule',
            index=models.Index(fields=['establishment', 'status'], name='action_plan_establi_aa853b_idx'),
        ),
        migrations.AddIndex(
            model_name='actionplanschedule',
            index=models.Index(fields=['action_plan', 'status'], name='action_plan_action__43081f_idx'),
        ),
        migrations.AddConstraint(
            model_name='actionplanschedule',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__gte', models.F('start_date'))), name='action_plan_schedule_end_date_on_or_after_start'),
        ),
        migrations.AddConstraint(
            model_name='actionplanschedule',
            constraint=models.CheckConstraint(condition=models.Q(('end_at__gt', models.F('start_at'))), name='action_plan_schedule_end_after_start_time'),
        ),
        migrations.AddIndex(
            model_name='actionplanexecution',
            index=models.Index(fields=['establishment', 'status', 'visible_from', 'last_activity_at'], name='ap_exec_feed_idx'),
        ),
        migrations.AddIndex(
            model_name='actionplanexecution',
            index=models.Index(fields=['source_signal', 'status'], name='ap_exec_signal_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='actionplanexecution',
            constraint=models.CheckConstraint(condition=models.Q(('pilot_business_unit__isnull', False)), name='action_plan_execution_pilot_business_unit_required'),
        ),
        migrations.AddConstraint(
            model_name='actionplanscheduleassignee',
            constraint=models.UniqueConstraint(fields=('action_plan_schedule', 'membership'), name='uniq_action_plan_schedule_assignee'),
        ),
        migrations.AddConstraint(
            model_name='actionplanscheduleassignee',
            constraint=models.CheckConstraint(condition=models.Q(('start_at__isnull', True), ('end_at__isnull', True), ('end_at__gt', models.F('start_at')), _connector='OR'), name='action_plan_schedule_assignee_end_after_start'),
        ),
        migrations.AddIndex(
            model_name='actionplantask',
            index=models.Index(fields=['action_plan', 'position'], name='action_plan_action__15f041_idx'),
        ),
        migrations.AddConstraint(
            model_name='actionplantask',
            constraint=models.UniqueConstraint(fields=('action_plan', 'position'), name='uniq_action_plan_task_position'),
        ),
        migrations.AddConstraint(
            model_name='actionplantask',
            constraint=models.CheckConstraint(condition=models.Q(('position__gte', 1), ('position__lte', 10)), name='action_plan_task_position_bounds'),
        ),
        migrations.AddConstraint(
            model_name='actionplantask',
            constraint=models.CheckConstraint(condition=models.Q(('business_unit__isnull', False)), name='action_plan_task_business_unit_required'),
        ),
        migrations.AddIndex(
            model_name='actionplanexecutiontask',
            index=models.Index(fields=['action_plan_execution', 'position'], name='action_plan_action__2ec13a_idx'),
        ),
        migrations.AddConstraint(
            model_name='actionplanexecutiontask',
            constraint=models.UniqueConstraint(fields=('action_plan_execution', 'position'), name='uniq_action_plan_execution_task_position'),
        ),
        migrations.AddConstraint(
            model_name='actionplanexecutiontask',
            constraint=models.CheckConstraint(condition=models.Q(('position__gte', 1), ('position__lte', 10)), name='action_plan_execution_task_position_bounds'),
        ),
    ]
