# Generated by Django 5.2.14 on 2026-07-11 14:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('action_plans', '0007_action_plan_execution_feed_pin'),
        ('establishments', '0021_establishmentmembership_push_enabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionPlanMixedSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submission_id', models.UUIDField()),
                ('request_hash', models.CharField(max_length=64)),
                ('action_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mixed_submissions', to='action_plans.actionplan')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='action_plan_mixed_submissions_created', to='establishments.establishmentmembership')),
                ('establishment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_plan_mixed_submissions', to='establishments.establishment')),
                ('execution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mixed_submissions', to='action_plans.actionplanexecution')),
                ('schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mixed_submissions', to='action_plans.actionplanschedule')),
            ],
        ),
        migrations.CreateModel(
            name='ActionPlanMixedOutboxEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('effect_key', models.CharField(max_length=255)),
                ('effect_type', models.CharField(choices=[('notification', 'Notification'), ('realtime_invalidation', 'Realtime invalidation')], max_length=32)),
                ('payload', models.JSONField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('processed', 'Processed'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('available_at', models.DateTimeField()),
                ('lease_expires_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, default='')),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('mixed_submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outbox_entries', to='action_plans.actionplanmixedsubmission')),
            ],
        ),
        migrations.AddConstraint(
            model_name='actionplanmixedsubmission',
            constraint=models.UniqueConstraint(fields=('establishment', 'action_plan', 'submission_id'), name='uniq_action_plan_mixed_submission'),
        ),
        migrations.AddConstraint(
            model_name='actionplanmixedsubmission',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('execution__isnull', True), ('schedule__isnull', True)), models.Q(('execution__isnull', False), ('schedule__isnull', False)), _connector='OR'), name='ap_mixed_submission_schedule_execution_pair'),
        ),
        migrations.AddIndex(
            model_name='actionplanmixedoutboxentry',
            index=models.Index(fields=['status', 'available_at'], name='ap_mixed_outbox_claim_idx'),
        ),
        migrations.AddIndex(
            model_name='actionplanmixedoutboxentry',
            index=models.Index(fields=['status', 'lease_expires_at'], name='ap_mixed_outbox_lease_idx'),
        ),
        migrations.AddConstraint(
            model_name='actionplanmixedoutboxentry',
            constraint=models.UniqueConstraint(fields=('mixed_submission', 'effect_key'), name='uniq_action_plan_mixed_outbox_effect'),
        ),
    ]
