# Generated by Django 5.2.14 on 2026-07-20 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('action_plans', '0010_chronology_owner_and_planning_submission'),
        ('establishments', '0027_drop_unique_active_or_invited_director'),
        ('signals', '0007_remove_signal_urgency'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='actionplanexecution',
            name='ap_exec_chronology_owner_matches_mode',
        ),
        migrations.RemoveConstraint(
            model_name='actionplanexecution',
            name='uniq_ap_exec_schedule_occurrence_individual',
        ),
        migrations.AddConstraint(
            model_name='actionplanexecution',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('chronology_owner_membership__isnull', True), ('use_shared_chronology', True)), models.Q(('chronology_owner_membership__isnull', False), ('use_shared_chronology', False)), _connector='OR'), name='ap_exec_chronology_owner_matches_mode'),
        ),
        migrations.AddConstraint(
            model_name='actionplanexecution',
            constraint=models.UniqueConstraint(condition=models.Q(('action_plan_schedule__isnull', False), ('chronology_owner_membership__isnull', False), ('use_shared_chronology', False)), fields=('action_plan_schedule', 'occurrence_date', 'chronology_owner_membership'), name='uniq_ap_exec_schedule_occurrence_individual'),
        ),
    ]
