# Generated by Django 5.2.14 on 2026-07-29 18:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('action_plans', '0012_execution_lifecycle_audit'),
        ('establishments', '0030_seed_onboarding_drafts'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionPlanExecutionReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stars', models.PositiveSmallIntegerField()),
                ('comment', models.TextField(blank=True, default='', max_length=2000)),
                ('reviewed_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('action_plan_execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='action_plans.actionplanexecution')),
                ('reviewer_membership', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='action_plan_execution_reviews', to='establishments.establishmentmembership')),
            ],
            options={
                'indexes': [models.Index(fields=['action_plan_execution', 'reviewed_at'], name='ap_exec_review_exec_at_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('stars__gte', 0), ('stars__lte', 5)), name='action_plan_execution_review_stars_bounds'), models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('action_plan_execution',), name='uniq_action_plan_execution_active_review')],
            },
        ),
    ]
