CHAT_MESSAGE_BODY_MAX_LENGTH = 2000
CHAT_GROUP_TITLE_MAX_LENGTH = 120
CHAT_ELIGIBLE_MEMBERSHIPS_QUERY_MAX_LENGTH = 100
CHAT_MESSAGE_RETENTION_DAYS = 7
CHAT_PURGE_BATCH_SIZE = 1000
CHAT_MESSAGE_SEND_RATE_LIMIT_PER_MINUTE = 30
CHAT_WS_TICKET_RATE_LIMIT = "30/minute"
