from django.urls import path

from houston.signals.api.views import (
    SignalArchiveView,
    SignalCancelView,
    SignalDetailView,
    SignalFeedView,
    SignalMarkInterestingView,
    SignalPinView,
    SignalQualifyRoutingOptionsView,
    SignalQualifyRoutingView,
    SignalResolutionRequestApproveView,
    SignalResolutionRequestCancelView,
    SignalResolutionRequestCreateView,
    SignalResolutionRequestRejectView,
    SignalResolveView,
    SignalUnpinView,
)

urlpatterns = [
    path(
        "establishments/<uuid:establishment_id>/signal-feed/",
        SignalFeedView.as_view(),
        name="signal-feed",
    ),
    path(
        "establishments/<uuid:establishment_id>/signals/qualify-routing-options/",
        SignalQualifyRoutingOptionsView.as_view(),
        name="signal-qualify-routing-options",
    ),
    path(
        "establishments/<uuid:establishment_id>/signals/<uuid:signal_id>/",
        SignalDetailView.as_view(),
        name="signal-detail",
    ),
    path(
        "establishments/<uuid:establishment_id>/signals/<uuid:signal_id>/pin/",
        SignalPinView.as_view(),
        name="signal-pin",
    ),
    path(
        "establishments/<uuid:establishment_id>/signals/<uuid:signal_id>/unpin/",
        SignalUnpinView.as_view(),
        name="signal-unpin",
    ),
    path(
        "establishments/<uuid:establishment_id>/signals/<uuid:signal_id>/cancel/",
        SignalCancelView.as_view(),
        name="signal-cancel",
    ),
    path(
        "establishments/<uuid:establishment_id>/signals/<uuid:signal_id>/resolve/",
        SignalResolveView.as_view(),
        name="signal-resolve",
    ),
    path(
        "establishments/<uuid:establishment_id>/signals/<uuid:signal_id>/mark-interesting/",
        SignalMarkInterestingView.as_view(),
        name="signal-mark-interesting",
    ),
    path(
        "establishments/<uuid:establishment_id>/signals/<uuid:signal_id>/archive/",
        SignalArchiveView.as_view(),
        name="signal-archive",
    ),
    path(
        "establishments/<uuid:establishment_id>/signals/<uuid:signal_id>/qualify-routing/",
        SignalQualifyRoutingView.as_view(),
        name="signal-qualify-routing",
    ),
    path(
        "establishments/<uuid:establishment_id>/signals/<uuid:signal_id>/resolution-requests/",
        SignalResolutionRequestCreateView.as_view(),
        name="signal-resolution-request-create",
    ),
    path(
        "establishments/<uuid:establishment_id>/signals/<uuid:signal_id>/resolution-requests/<uuid:request_id>/approve/",
        SignalResolutionRequestApproveView.as_view(),
        name="signal-resolution-request-approve",
    ),
    path(
        "establishments/<uuid:establishment_id>/signals/<uuid:signal_id>/resolution-requests/<uuid:request_id>/reject/",
        SignalResolutionRequestRejectView.as_view(),
        name="signal-resolution-request-reject",
    ),
    path(
        "establishments/<uuid:establishment_id>/signals/<uuid:signal_id>/resolution-requests/<uuid:request_id>/cancel/",
        SignalResolutionRequestCancelView.as_view(),
        name="signal-resolution-request-cancel",
    ),
]
