from django.urls import path

from houston.signals.api.views import (
    SignalCancelView,
    SignalDetailView,
    SignalFeedView,
    SignalMarkInterestingView,
    SignalPinView,
    SignalQualifyRoutingOptionsView,
    SignalQualifyRoutingView,
    SignalResolveView,
    SignalUnpinView,
)

urlpatterns = [
    path(
        "establishments/<uuid:establishment_id>/signal-feed/",
        SignalFeedView.as_view(),
        name="signal-feed",
    ),
    path(
        "establishments/<uuid:establishment_id>/signals/qualify-routing-options/",
        SignalQualifyRoutingOptionsView.as_view(),
        name="signal-qualify-routing-options",
    ),
    path(
        "establishments/<uuid:establishment_id>/signals/<uuid:signal_id>/",
        SignalDetailView.as_view(),
        name="signal-detail",
    ),
    path(
        "establishments/<uuid:establishment_id>/signals/<uuid:signal_id>/pin/",
        SignalPinView.as_view(),
        name="signal-pin",
    ),
    path(
        "establishments/<uuid:establishment_id>/signals/<uuid:signal_id>/unpin/",
        SignalUnpinView.as_view(),
        name="signal-unpin",
    ),
    path(
        "establishments/<uuid:establishment_id>/signals/<uuid:signal_id>/cancel/",
        SignalCancelView.as_view(),
        name="signal-cancel",
    ),
    path(
        "establishments/<uuid:establishment_id>/signals/<uuid:signal_id>/resolve/",
        SignalResolveView.as_view(),
        name="signal-resolve",
    ),
    path(
        "establishments/<uuid:establishment_id>/signals/<uuid:signal_id>/mark-interesting/",
        SignalMarkInterestingView.as_view(),
        name="signal-mark-interesting",
    ),
    path(
        "establishments/<uuid:establishment_id>/signals/<uuid:signal_id>/qualify-routing/",
        SignalQualifyRoutingView.as_view(),
        name="signal-qualify-routing",
    ),
]
