# Generated by Django 5.2.14 on 2026-05-28 16:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('establishments', '0006_operationaldomain_managed_by_onboarding_proposal_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIUsageLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ai_domain', models.CharField(choices=[('onboarding', 'Onboarding')], default='onboarding', max_length=40)),
                ('provider', models.CharField(max_length=80)),
                ('model', models.CharField(blank=True, default='', max_length=120)),
                ('prompt_version', models.CharField(max_length=80)),
                ('schema_version', models.CharField(max_length=80)),
                ('status', models.CharField(choices=[('started', 'Started'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('fallback_succeeded', 'Fallback succeeded'), ('fallback_failed', 'Fallback failed')], max_length=40)),
                ('latency_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('input_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('output_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('total_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, default='', max_length=80)),
                ('correlation_id', models.UUIDField(db_index=True)),
                ('establishment', models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_usage_logs', to='establishments.establishment')),
                ('onboarding_proposal', models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_usage_logs', to='establishments.onboardingproposal')),
                ('onboarding_session', models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_usage_logs', to='establishments.onboardingsession')),
            ],
            options={
                'indexes': [models.Index(fields=['ai_domain', 'status'], name='ai_usage_domain_status_idx'), models.Index(fields=['provider', 'model'], name='ai_usage_provider_model_idx'), models.Index(fields=['establishment'], name='ai_usage_est_idx'), models.Index(fields=['onboarding_session'], name='ai_usage_session_idx'), models.Index(fields=['onboarding_proposal'], name='ai_usage_prop_idx'), models.Index(fields=['created_at'], name='ai_usage_created_idx')],
            },
        ),
    ]
