# Generated by Django 5.2.14 on 2026-06-02 12:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ai", "0002_aiusagelog_observation_alter_aiusagelog_ai_domain_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aiusagelog",
            name="ai_domain",
            field=models.CharField(
                choices=[
                    ("onboarding", "Onboarding"),
                    ("transcription", "Transcription"),
                    ("observation_pipeline", "Observation pipeline"),
                ],
                default="onboarding",
                max_length=40,
            ),
        ),
    ]
