from django.urls import path
from houston.chat.api.views import (
    ChatAddParticipantView,
    ChatConversationDetailView,
    ChatConversationListView,
    ChatConversationMessagesView,
    ChatConversationSeenView,
    ChatCreateDmView,
    ChatCreateGroupView,
    ChatEligibleMembershipsView,
    ChatLeaveConversationView,
    ChatPromoteParticipantView,
    ChatRemoveParticipantView,
    ChatSettingsView,
    ChatStatusView,
    ChatWsTicketView,
)

urlpatterns = [
    path(
        "establishments/<uuid:establishment_id>/chat/ws-ticket/",
        ChatWsTicketView.as_view(),
        name="chat-ws-ticket",
    ),
    path(
        "establishments/<uuid:establishment_id>/chat/status/",
        ChatStatusView.as_view(),
        name="chat-status",
    ),
    path(
        "establishments/<uuid:establishment_id>/chat/conversations/",
        ChatConversationListView.as_view(),
        name="chat-conversation-list",
    ),
    path(
        "establishments/<uuid:establishment_id>/chat/conversations/dm/",
        ChatCreateDmView.as_view(),
        name="chat-conversation-create-dm",
    ),
    path(
        "establishments/<uuid:establishment_id>/chat/conversations/groups/",
        ChatCreateGroupView.as_view(),
        name="chat-conversation-create-group",
    ),
    path(
        "establishments/<uuid:establishment_id>/chat/conversations/<uuid:conversation_id>/",
        ChatConversationDetailView.as_view(),
        name="chat-conversation-detail",
    ),
    path(
        "establishments/<uuid:establishment_id>/chat/conversations/<uuid:conversation_id>/messages/",
        ChatConversationMessagesView.as_view(),
        name="chat-conversation-messages",
    ),
    path(
        "establishments/<uuid:establishment_id>/chat/conversations/<uuid:conversation_id>/seen/",
        ChatConversationSeenView.as_view(),
        name="chat-conversation-seen",
    ),
    path(
        "establishments/<uuid:establishment_id>/chat/conversations/<uuid:conversation_id>/participants/",
        ChatAddParticipantView.as_view(),
        name="chat-conversation-add-participant",
    ),
    path(
        "establishments/<uuid:establishment_id>/chat/conversations/<uuid:conversation_id>/participants/<uuid:membership_id>/",
        ChatRemoveParticipantView.as_view(),
        name="chat-conversation-remove-participant",
    ),
    path(
        "establishments/<uuid:establishment_id>/chat/conversations/<uuid:conversation_id>/participants/<uuid:membership_id>/promote/",
        ChatPromoteParticipantView.as_view(),
        name="chat-conversation-promote-participant",
    ),
    path(
        "establishments/<uuid:establishment_id>/chat/conversations/<uuid:conversation_id>/leave/",
        ChatLeaveConversationView.as_view(),
        name="chat-conversation-leave",
    ),
    path(
        "establishments/<uuid:establishment_id>/chat/eligible-memberships/",
        ChatEligibleMembershipsView.as_view(),
        name="chat-eligible-memberships",
    ),
    path(
        "establishments/<uuid:establishment_id>/chat/settings/",
        ChatSettingsView.as_view(),
        name="chat-settings",
    ),
]
