# Generated by Django 5.2.14 on 2026-09-19 14:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformOperatorAccess',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('granted_at', models.DateTimeField()),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='platform_operator_access', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PlatformLifecycleEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(max_length=64)),
                ('resource_type', models.CharField(max_length=64)),
                ('resource_id', models.UUIDField(blank=True, null=True)),
                ('justification', models.TextField(blank=True, default='')),
                ('result', models.CharField(choices=[('ok', 'Ok'), ('denied', 'Denied'), ('failed', 'Failed')], max_length=16)),
                ('error_code', models.CharField(blank=True, default='', max_length=64)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='platform_lifecycle_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['created_at'], name='platform_pl_created_c87507_idx'), models.Index(fields=['resource_type', 'resource_id'], name='platform_pl_resourc_b04c5a_idx')],
            },
        ),
    ]
