from __future__ import annotations

CHECKLIST_TITLE_MAX_LENGTH = 200
CHECKLIST_DESCRIPTION_MAX_LENGTH = 2000
CHECKLIST_TASK_MAX_LENGTH = 500
CHECKLIST_SKIPPED_REASON_MAX_LENGTH = 500

RECURRENCE_DAY_MONDAY = "monday"
RECURRENCE_DAY_TUESDAY = "tuesday"
RECURRENCE_DAY_WEDNESDAY = "wednesday"
RECURRENCE_DAY_THURSDAY = "thursday"
RECURRENCE_DAY_FRIDAY = "friday"
RECURRENCE_DAY_SATURDAY = "saturday"
RECURRENCE_DAY_SUNDAY = "sunday"

RECURRENCE_DAYS = frozenset(
    {
        RECURRENCE_DAY_MONDAY,
        RECURRENCE_DAY_TUESDAY,
        RECURRENCE_DAY_WEDNESDAY,
        RECURRENCE_DAY_THURSDAY,
        RECURRENCE_DAY_FRIDAY,
        RECURRENCE_DAY_SATURDAY,
        RECURRENCE_DAY_SUNDAY,
    }
)

TEMPLATE_STATUS_ACTIVE = "active"
TEMPLATE_STATUS_INACTIVE = "inactive"
TEMPLATE_STATUSES = frozenset({TEMPLATE_STATUS_ACTIVE, TEMPLATE_STATUS_INACTIVE})

ASSIGNMENT_STATUS_ACTIVE = "active"
ASSIGNMENT_STATUS_INACTIVE = "inactive"
ASSIGNMENT_STATUSES = frozenset({ASSIGNMENT_STATUS_ACTIVE, ASSIGNMENT_STATUS_INACTIVE})

EXECUTION_STATUS_ASSIGNED = "assigned"
EXECUTION_STATUS_IN_PROGRESS = "in_progress"
EXECUTION_STATUS_DONE = "done"
EXECUTION_STATUS_CANCELED = "canceled"
EXECUTION_STATUSES = frozenset(
    {
        EXECUTION_STATUS_ASSIGNED,
        EXECUTION_STATUS_IN_PROGRESS,
        EXECUTION_STATUS_DONE,
        EXECUTION_STATUS_CANCELED,
    }
)

ACTIVE_EXECUTION_STATUSES = frozenset(
    {
        EXECUTION_STATUS_ASSIGNED,
        EXECUTION_STATUS_IN_PROGRESS,
    }
)

TERMINAL_EXECUTION_STATUSES = frozenset(
    {
        EXECUTION_STATUS_DONE,
        EXECUTION_STATUS_CANCELED,
    }
)

EXECUTION_FEED_STATUSES = ACTIVE_EXECUTION_STATUSES

TASK_STATUS_PENDING = "pending"
TASK_STATUS_DONE = "done"
TASK_STATUS_SKIPPED = "skipped"
TASK_STATUS_OBSERVATION_CREATED = "observation_created"
TASK_STATUSES = frozenset(
    {
        TASK_STATUS_PENDING,
        TASK_STATUS_DONE,
        TASK_STATUS_SKIPPED,
        TASK_STATUS_OBSERVATION_CREATED,
    }
)

TREATED_TASK_STATUSES = frozenset(
    {
        TASK_STATUS_DONE,
        TASK_STATUS_SKIPPED,
        TASK_STATUS_OBSERVATION_CREATED,
    }
)

CHECKLIST_TYPE_SHARED = "shared"
CHECKLIST_TYPE_PERSONAL = "personal"
CHECKLIST_TYPES = frozenset({CHECKLIST_TYPE_SHARED, CHECKLIST_TYPE_PERSONAL})
