# Generated by Django 5.2.14 on 2026-09-19 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='has_been_operational',
            field=models.BooleanField(default=False),
        ),
    ]
