from django.urls import path

from houston.accounts.api.views import DirectorInvitationAcceptView
from houston.establishments.api.views import (
    CatalogActivitySubjectSuggestView,
    CatalogBusinessUnitSuggestView,
    EstablishmentActivitySubjectCreateView,
    EstablishmentActivitySubjectDeactivateView,
    EstablishmentBusinessUnitDeactivateView,
    EstablishmentBusinessUnitDetailView,
    EstablishmentBusinessUnitTreeView,
    MembershipDeactivateView,
    MembershipDetailView,
    MembershipInvitationView,
    MembershipListView,
    OnboardingSessionActivateView,
    OnboardingSessionActivationSummaryView,
    OnboardingSessionCreateView,
    OnboardingSessionDescriptionView,
    OnboardingSessionDetailView,
    OnboardingSessionDirectorInvitationView,
    OnboardingSessionMarkReadyView,
    OnboardingSessionProposalApplyView,
    OnboardingSessionProposalDetailView,
    OnboardingSessionProposalListView,
    OnboardingSessionProposalRejectView,
    OnboardingSessionProposalSubmitView,
    OnboardingSessionRuntimeConfigView,
    ScopedUserSearchView,
    WorkspaceSummaryView,
)

urlpatterns = [
    path(
        "invitations/<str:token>/accept/",
        DirectorInvitationAcceptView.as_view(),
        name="director-invitation-accept",
    ),
    path(
        "onboarding-sessions/",
        OnboardingSessionCreateView.as_view(),
        name="onboarding-session-create",
    ),
    path(
        "onboarding-sessions/<uuid:session_id>/",
        OnboardingSessionDetailView.as_view(),
        name="onboarding-session-detail",
    ),
    path(
        "onboarding-sessions/<uuid:session_id>/description/",
        OnboardingSessionDescriptionView.as_view(),
        name="onboarding-session-description",
    ),
    path(
        "onboarding-sessions/<uuid:session_id>/runtime-config/",
        OnboardingSessionRuntimeConfigView.as_view(),
        name="onboarding-session-runtime-config",
    ),
    path(
        "onboarding-sessions/<uuid:session_id>/activation-summary/",
        OnboardingSessionActivationSummaryView.as_view(),
        name="onboarding-session-activation-summary",
    ),
    path(
        "onboarding-sessions/<uuid:session_id>/director-invitations/",
        OnboardingSessionDirectorInvitationView.as_view(),
        name="onboarding-session-director-invitation",
    ),
    path(
        "onboarding-sessions/<uuid:session_id>/mark-ready/",
        OnboardingSessionMarkReadyView.as_view(),
        name="onboarding-session-mark-ready",
    ),
    path(
        "onboarding-sessions/<uuid:session_id>/activate/",
        OnboardingSessionActivateView.as_view(),
        name="onboarding-session-activate",
    ),
    path(
        "onboarding-sessions/<uuid:session_id>/proposals/",
        OnboardingSessionProposalListView.as_view(),
        name="onboarding-session-proposal-list",
    ),
    path(
        "onboarding-sessions/<uuid:session_id>/proposals/<uuid:proposal_id>/",
        OnboardingSessionProposalDetailView.as_view(),
        name="onboarding-session-proposal-detail",
    ),
    path(
        "onboarding-sessions/<uuid:session_id>/proposals/<uuid:proposal_id>/reject/",
        OnboardingSessionProposalRejectView.as_view(),
        name="onboarding-session-proposal-reject",
    ),
    path(
        "onboarding-sessions/<uuid:session_id>/proposals/<uuid:proposal_id>/submit/",
        OnboardingSessionProposalSubmitView.as_view(),
        name="onboarding-session-proposal-submit",
    ),
    path(
        "onboarding-sessions/<uuid:session_id>/proposals/<uuid:proposal_id>/apply/",
        OnboardingSessionProposalApplyView.as_view(),
        name="onboarding-session-proposal-apply",
    ),
    path(
        "establishments/<uuid:establishment_id>/business-units/",
        EstablishmentBusinessUnitTreeView.as_view(),
        name="establishment-business-units",
    ),
    path(
        "establishments/<uuid:establishment_id>/business-units/<uuid:business_unit_id>/",
        EstablishmentBusinessUnitDetailView.as_view(),
        name="establishment-business-unit-detail",
    ),
    path(
        "establishments/<uuid:establishment_id>/business-units/<uuid:business_unit_id>/deactivate/",
        EstablishmentBusinessUnitDeactivateView.as_view(),
        name="establishment-business-unit-deactivate",
    ),
    path(
        "establishments/<uuid:establishment_id>/business-units/<uuid:business_unit_id>/activity-subjects/",
        EstablishmentActivitySubjectCreateView.as_view(),
        name="establishment-activity-subject-create",
    ),
    path(
        "establishments/<uuid:establishment_id>/activity-subjects/<uuid:activity_subject_id>/deactivate/",
        EstablishmentActivitySubjectDeactivateView.as_view(),
        name="establishment-activity-subject-deactivate",
    ),
    path(
        "catalog/business-units/suggest/",
        CatalogBusinessUnitSuggestView.as_view(),
        name="catalog-business-units-suggest",
    ),
    path(
        "catalog/activity-subjects/suggest/",
        CatalogActivitySubjectSuggestView.as_view(),
        name="catalog-activity-subjects-suggest",
    ),
    path(
        "establishments/<uuid:establishment_id>/workspace-summary/",
        WorkspaceSummaryView.as_view(),
        name="establishment-workspace-summary",
    ),
    path(
        "establishments/<uuid:establishment_id>/membership-invitations/",
        MembershipInvitationView.as_view(),
        name="establishment-membership-invitation",
    ),
    path(
        "establishments/<uuid:establishment_id>/memberships/",
        MembershipListView.as_view(),
        name="establishment-membership-list",
    ),
    path(
        "establishments/<uuid:establishment_id>/memberships/<uuid:membership_id>/",
        MembershipDetailView.as_view(),
        name="establishment-membership-detail",
    ),
    path(
        "establishments/<uuid:establishment_id>/memberships/<uuid:membership_id>/deactivate/",
        MembershipDeactivateView.as_view(),
        name="establishment-membership-deactivate",
    ),
    path(
        "establishments/<uuid:establishment_id>/users/search/",
        ScopedUserSearchView.as_view(),
        name="establishment-user-search",
    ),
]
