from django.urls import path

from houston.accounts.api.views import DirectorInvitationAcceptView
from houston.establishments.api.establishment_admin_views import (
    EstablishmentAdminMemberFilterOptionsView,
    EstablishmentAdminMembershipActivateView,
    EstablishmentAdminMembershipDeactivateView,
    EstablishmentAdminMembershipDetailView,
    EstablishmentAdminMembershipInvitationView,
    EstablishmentAdminMembershipListView,
    EstablishmentAdminOverviewView,
)
from houston.establishments.api.organization_admin_views import (
    OrganizationAdminEstablishmentListView,
    OrganizationAdminMemberFilterOptionsView,
    OrganizationAdminMemberListView,
    OrganizationAdminOverviewView,
    OrganizationAdminOwnerInvitationView,
    OrganizationAdminOwnerListView,
)
from houston.establishments.api.safety_views import (
    ContentReportCreateView,
    MembershipBlockView,
)
from houston.establishments.api.views import (
    CatalogActivitySubjectSuggestView,
    CatalogBusinessUnitSuggestView,
    EstablishmentActivitySubjectCreateView,
    EstablishmentActivitySubjectDeactivateView,
    EstablishmentActivitySubjectReactivateView,
    EstablishmentBusinessUnitDeactivateView,
    EstablishmentBusinessUnitDetailView,
    EstablishmentBusinessUnitReactivateView,
    EstablishmentBusinessUnitTreeView,
    MembershipActivateView,
    MembershipDeactivateView,
    MembershipDetailView,
    MembershipInvitationView,
    MembershipListView,
    MembershipReinviteView,
    ScopedUserSearchView,
)

urlpatterns = [
    path(
        "organizations/<uuid:organization_id>/",
        OrganizationAdminOverviewView.as_view(),
        name="organization-admin-overview",
    ),
    path(
        "organizations/<uuid:organization_id>/establishments/",
        OrganizationAdminEstablishmentListView.as_view(),
        name="organization-admin-establishments",
    ),
    path(
        "organizations/<uuid:organization_id>/members/filter-options/",
        OrganizationAdminMemberFilterOptionsView.as_view(),
        name="organization-admin-member-filter-options",
    ),
    path(
        "organizations/<uuid:organization_id>/members/",
        OrganizationAdminMemberListView.as_view(),
        name="organization-admin-members",
    ),
    path(
        "organizations/<uuid:organization_id>/owners/",
        OrganizationAdminOwnerListView.as_view(),
        name="organization-admin-owners",
    ),
    path(
        "organizations/<uuid:organization_id>/owner-invitations/",
        OrganizationAdminOwnerInvitationView.as_view(),
        name="organization-admin-owner-invitations",
    ),
    path(
        "invitations/accept/",
        DirectorInvitationAcceptView.as_view(),
        name="director-invitation-accept",
    ),
    path(
        "establishments/<uuid:establishment_id>/business-units/",
        EstablishmentBusinessUnitTreeView.as_view(),
        name="establishment-business-units",
    ),
    path(
        "establishments/<uuid:establishment_id>/business-units/<uuid:business_unit_id>/",
        EstablishmentBusinessUnitDetailView.as_view(),
        name="establishment-business-unit-detail",
    ),
    path(
        "establishments/<uuid:establishment_id>/business-units/<uuid:business_unit_id>/deactivate/",
        EstablishmentBusinessUnitDeactivateView.as_view(),
        name="establishment-business-unit-deactivate",
    ),
    path(
        "establishments/<uuid:establishment_id>/business-units/<uuid:business_unit_id>/reactivate/",
        EstablishmentBusinessUnitReactivateView.as_view(),
        name="establishment-business-unit-reactivate",
    ),
    path(
        "establishments/<uuid:establishment_id>/business-units/<uuid:business_unit_id>/activity-subjects/",
        EstablishmentActivitySubjectCreateView.as_view(),
        name="establishment-activity-subject-create",
    ),
    path(
        "establishments/<uuid:establishment_id>/activity-subjects/<uuid:activity_subject_id>/reactivate/",
        EstablishmentActivitySubjectReactivateView.as_view(),
        name="establishment-activity-subject-reactivate",
    ),
    path(
        "establishments/<uuid:establishment_id>/activity-subjects/<uuid:activity_subject_id>/deactivate/",
        EstablishmentActivitySubjectDeactivateView.as_view(),
        name="establishment-activity-subject-deactivate",
    ),
    path(
        "catalog/business-units/suggest/",
        CatalogBusinessUnitSuggestView.as_view(),
        name="catalog-business-units-suggest",
    ),
    path(
        "catalog/activity-subjects/suggest/",
        CatalogActivitySubjectSuggestView.as_view(),
        name="catalog-activity-subjects-suggest",
    ),
    path(
        "establishments/<uuid:establishment_id>/admin/overview/",
        EstablishmentAdminOverviewView.as_view(),
        name="establishment-admin-overview",
    ),
    path(
        "establishments/<uuid:establishment_id>/admin/memberships/filter-options/",
        EstablishmentAdminMemberFilterOptionsView.as_view(),
        name="establishment-admin-membership-filter-options",
    ),
    path(
        "establishments/<uuid:establishment_id>/admin/memberships/",
        EstablishmentAdminMembershipListView.as_view(),
        name="establishment-admin-membership-list",
    ),
    path(
        "establishments/<uuid:establishment_id>/admin/membership-invitations/",
        EstablishmentAdminMembershipInvitationView.as_view(),
        name="establishment-admin-membership-invitation",
    ),
    path(
        "establishments/<uuid:establishment_id>/admin/memberships/<uuid:membership_id>/",
        EstablishmentAdminMembershipDetailView.as_view(),
        name="establishment-admin-membership-detail",
    ),
    path(
        "establishments/<uuid:establishment_id>/admin/memberships/<uuid:membership_id>/deactivate/",
        EstablishmentAdminMembershipDeactivateView.as_view(),
        name="establishment-admin-membership-deactivate",
    ),
    path(
        "establishments/<uuid:establishment_id>/admin/memberships/<uuid:membership_id>/activate/",
        EstablishmentAdminMembershipActivateView.as_view(),
        name="establishment-admin-membership-activate",
    ),
    path(
        "establishments/<uuid:establishment_id>/membership-invitations/",
        MembershipInvitationView.as_view(),
        name="establishment-membership-invitation",
    ),
    path(
        "establishments/<uuid:establishment_id>/memberships/",
        MembershipListView.as_view(),
        name="establishment-membership-list",
    ),
    path(
        "establishments/<uuid:establishment_id>/memberships/<uuid:membership_id>/",
        MembershipDetailView.as_view(),
        name="establishment-membership-detail",
    ),
    path(
        "establishments/<uuid:establishment_id>/memberships/<uuid:membership_id>/reinvite/",
        MembershipReinviteView.as_view(),
        name="establishment-membership-reinvite",
    ),
    path(
        "establishments/<uuid:establishment_id>/memberships/<uuid:membership_id>/deactivate/",
        MembershipDeactivateView.as_view(),
        name="establishment-membership-deactivate",
    ),
    path(
        "establishments/<uuid:establishment_id>/memberships/<uuid:membership_id>/activate/",
        MembershipActivateView.as_view(),
        name="establishment-membership-activate",
    ),
    path(
        "establishments/<uuid:establishment_id>/users/search/",
        ScopedUserSearchView.as_view(),
        name="establishment-user-search",
    ),
    path(
        "establishments/<uuid:establishment_id>/memberships/<uuid:membership_id>/block/",
        MembershipBlockView.as_view(),
        name="establishment-membership-block",
    ),
    path(
        "establishments/<uuid:establishment_id>/content-reports/",
        ContentReportCreateView.as_view(),
        name="establishment-content-report-create",
    ),
]
