from __future__ import annotations

from typing import Literal

ExecutionFeedViewMode = Literal["personal", "general"]

ACTION_PLAN_TITLE_MAX_LENGTH = 200
ACTION_PLAN_DESCRIPTION_MAX_LENGTH = 2000
ACTION_PLAN_TASK_MAX_LENGTH = 500
ACTION_PLAN_SKIPPED_REASON_MAX_LENGTH = 500
ACTION_PLAN_EXECUTION_REVIEW_COMMENT_MAX_LENGTH = 2000

MAX_TASKS_PER_PLAN = 10
MIN_TASK_POSITION = 1
MAX_TASK_POSITION = 10

RECURRENCE_DAY_MONDAY = "monday"
RECURRENCE_DAY_TUESDAY = "tuesday"
RECURRENCE_DAY_WEDNESDAY = "wednesday"
RECURRENCE_DAY_THURSDAY = "thursday"
RECURRENCE_DAY_FRIDAY = "friday"
RECURRENCE_DAY_SATURDAY = "saturday"
RECURRENCE_DAY_SUNDAY = "sunday"

RECURRENCE_DAYS = frozenset(
    {
        RECURRENCE_DAY_MONDAY,
        RECURRENCE_DAY_TUESDAY,
        RECURRENCE_DAY_WEDNESDAY,
        RECURRENCE_DAY_THURSDAY,
        RECURRENCE_DAY_FRIDAY,
        RECURRENCE_DAY_SATURDAY,
        RECURRENCE_DAY_SUNDAY,
    }
)

CATALOG_STATUS_ACTIVE = "active"
CATALOG_STATUS_INACTIVE = "inactive"
CATALOG_STATUSES = frozenset({CATALOG_STATUS_ACTIVE, CATALOG_STATUS_INACTIVE})

SCHEDULE_STATUS_ACTIVE = "active"
SCHEDULE_STATUS_INACTIVE = "inactive"
SCHEDULE_STATUSES = frozenset({SCHEDULE_STATUS_ACTIVE, SCHEDULE_STATUS_INACTIVE})

EXECUTION_STATUS_SCHEDULED = "scheduled"
EXECUTION_STATUS_IN_PROGRESS = "in_progress"
EXECUTION_STATUS_PENDING_VALIDATION = "pending_validation"
EXECUTION_STATUS_DONE = "done"
EXECUTION_STATUS_CANCELED = "canceled"
EXECUTION_STATUSES = frozenset(
    {
        EXECUTION_STATUS_SCHEDULED,
        EXECUTION_STATUS_IN_PROGRESS,
        EXECUTION_STATUS_PENDING_VALIDATION,
        EXECUTION_STATUS_DONE,
        EXECUTION_STATUS_CANCELED,
    }
)

ACTIVE_EXECUTION_STATUSES = frozenset(
    {
        EXECUTION_STATUS_IN_PROGRESS,
        EXECUTION_STATUS_PENDING_VALIDATION,
    }
)

CANCELABLE_EXECUTION_STATUSES = frozenset(
    {
        EXECUTION_STATUS_SCHEDULED,
        EXECUTION_STATUS_IN_PROGRESS,
        EXECUTION_STATUS_PENDING_VALIDATION,
    }
)

SIGNAL_BLOCKING_EXECUTION_STATUSES = frozenset(
    {
        EXECUTION_STATUS_SCHEDULED,
        EXECUTION_STATUS_IN_PROGRESS,
        EXECUTION_STATUS_PENDING_VALIDATION,
    }
)

# Cursor-paginated feed items exclude scheduled (preview via scheduled_items).
EXECUTION_FEED_CURSOR_STATUSES = frozenset(
    {
        EXECUTION_STATUS_IN_PROGRESS,
        EXECUTION_STATUS_PENDING_VALIDATION,
        EXECUTION_STATUS_DONE,
        EXECUTION_STATUS_CANCELED,
    }
)

EXECUTION_FEED_STATUSES = EXECUTION_STATUSES

TERMINAL_EXECUTION_STATUSES = frozenset(
    {
        EXECUTION_STATUS_DONE,
        EXECUTION_STATUS_CANCELED,
    }
)

SCHEDULED_FEED_PREVIEW_LIMIT = 50

CANCEL_ORIGIN_MANUAL = "manual"
CANCEL_ORIGIN_SCHEDULE_SYNC = "schedule_sync"
CANCEL_ORIGINS = frozenset(
    {
        CANCEL_ORIGIN_MANUAL,
        CANCEL_ORIGIN_SCHEDULE_SYNC,
    }
)

# ActionPlanExecutionLifecycleEvent.event_type — append-only execution lifecycle journal.
EXECUTION_LIFECYCLE_EVENT_CREATED = "action_plan_execution.created"
EXECUTION_LIFECYCLE_EVENT_STARTED = "action_plan_execution.started"
EXECUTION_LIFECYCLE_EVENT_MARKED_DONE = "action_plan_execution.marked_done"
EXECUTION_LIFECYCLE_EVENT_VALIDATED = "action_plan_execution.validated"
EXECUTION_LIFECYCLE_EVENT_CANCELED = "action_plan_execution.canceled"
EXECUTION_LIFECYCLE_EVENT_REOPENED = "action_plan_execution.reopened"
EXECUTION_LIFECYCLE_EVENT_REACTIVATED = "action_plan_execution.reactivated"
EXECUTION_LIFECYCLE_EVENT_TYPE_VALUES = frozenset(
    {
        EXECUTION_LIFECYCLE_EVENT_CREATED,
        EXECUTION_LIFECYCLE_EVENT_STARTED,
        EXECUTION_LIFECYCLE_EVENT_MARKED_DONE,
        EXECUTION_LIFECYCLE_EVENT_VALIDATED,
        EXECUTION_LIFECYCLE_EVENT_CANCELED,
        EXECUTION_LIFECYCLE_EVENT_REOPENED,
        EXECUTION_LIFECYCLE_EVENT_REACTIVATED,
    }
)

# Allowlisted keys for ActionPlanExecutionLifecycleEvent.metadata_safe (no user free text).
EXECUTION_LIFECYCLE_METADATA_SAFE_KEYS = frozenset(
    {
        "initial_status",
        "cancel_origin",
        "reactivation_origin",
        "to_status",
    }
)

TASK_STATUS_PENDING = "pending"
TASK_STATUS_DONE = "done"
TASK_STATUS_SKIPPED = "skipped"
TASK_STATUS_OBSERVATION_CREATED = "observation_created"
TASK_STATUSES = frozenset(
    {
        TASK_STATUS_PENDING,
        TASK_STATUS_DONE,
        TASK_STATUS_SKIPPED,
        TASK_STATUS_OBSERVATION_CREATED,
    }
)

TERMINAL_TASK_STATUSES = frozenset(
    {
        TASK_STATUS_DONE,
        TASK_STATUS_SKIPPED,
        TASK_STATUS_OBSERVATION_CREATED,
    }
)

CONTRIBUTION_STATUS_IN_PROGRESS = "in_progress"
CONTRIBUTION_STATUS_DONE = "done"
CONTRIBUTION_STATUSES = frozenset(
    {
        CONTRIBUTION_STATUS_IN_PROGRESS,
        CONTRIBUTION_STATUS_DONE,
    }
)
