from __future__ import annotations

ACTION_PLAN_TITLE_MAX_LENGTH = 200
ACTION_PLAN_DESCRIPTION_MAX_LENGTH = 2000
ACTION_PLAN_TASK_MAX_LENGTH = 500
ACTION_PLAN_SKIPPED_REASON_MAX_LENGTH = 500

MAX_TASKS_PER_PLAN = 10
MIN_TASK_POSITION = 1
MAX_TASK_POSITION = 10

RECURRENCE_DAY_MONDAY = "monday"
RECURRENCE_DAY_TUESDAY = "tuesday"
RECURRENCE_DAY_WEDNESDAY = "wednesday"
RECURRENCE_DAY_THURSDAY = "thursday"
RECURRENCE_DAY_FRIDAY = "friday"
RECURRENCE_DAY_SATURDAY = "saturday"
RECURRENCE_DAY_SUNDAY = "sunday"

RECURRENCE_DAYS = frozenset(
    {
        RECURRENCE_DAY_MONDAY,
        RECURRENCE_DAY_TUESDAY,
        RECURRENCE_DAY_WEDNESDAY,
        RECURRENCE_DAY_THURSDAY,
        RECURRENCE_DAY_FRIDAY,
        RECURRENCE_DAY_SATURDAY,
        RECURRENCE_DAY_SUNDAY,
    }
)

CATALOG_STATUS_ACTIVE = "active"
CATALOG_STATUS_INACTIVE = "inactive"
CATALOG_STATUSES = frozenset({CATALOG_STATUS_ACTIVE, CATALOG_STATUS_INACTIVE})

SCHEDULE_STATUS_ACTIVE = "active"
SCHEDULE_STATUS_INACTIVE = "inactive"
SCHEDULE_STATUSES = frozenset({SCHEDULE_STATUS_ACTIVE, SCHEDULE_STATUS_INACTIVE})

EXECUTION_STATUS_IN_PROGRESS = "in_progress"
EXECUTION_STATUS_PENDING_VALIDATION = "pending_validation"
EXECUTION_STATUS_DONE = "done"
EXECUTION_STATUS_CANCELED = "canceled"
EXECUTION_STATUSES = frozenset(
    {
        EXECUTION_STATUS_IN_PROGRESS,
        EXECUTION_STATUS_PENDING_VALIDATION,
        EXECUTION_STATUS_DONE,
        EXECUTION_STATUS_CANCELED,
    }
)

ACTIVE_EXECUTION_STATUSES = frozenset(
    {
        EXECUTION_STATUS_IN_PROGRESS,
        EXECUTION_STATUS_PENDING_VALIDATION,
    }
)

TERMINAL_EXECUTION_STATUSES = frozenset(
    {
        EXECUTION_STATUS_DONE,
        EXECUTION_STATUS_CANCELED,
    }
)

TASK_STATUS_PENDING = "pending"
TASK_STATUS_DONE = "done"
TASK_STATUS_SKIPPED = "skipped"
TASK_STATUS_OBSERVATION_CREATED = "observation_created"
TASK_STATUSES = frozenset(
    {
        TASK_STATUS_PENDING,
        TASK_STATUS_DONE,
        TASK_STATUS_SKIPPED,
        TASK_STATUS_OBSERVATION_CREATED,
    }
)
