# Generated by Django 5.2.14 on 2026-06-02 12:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("observations", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="observationprocessing",
            name="attempt_count",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="observationprocessing",
            name="outcome",
            field=models.CharField(
                blank=True,
                choices=[
                    ("signals_created", "Signals created"),
                    ("signal_aggregated", "Signal aggregated"),
                    ("no_signal_created", "No signal created"),
                    ("not_actionable", "Not actionable"),
                ],
                default="",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="observationprocessing",
            name="processed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="observationprocessing",
            name="processing_started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
