# Generated by Django 5.2.14 on 2026-06-09 15:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("establishments", "0018_establishment_chat_enabled"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatConversation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "type",
                    models.CharField(
                        choices=[("dm", "Direct message"), ("group", "Group")], max_length=16
                    ),
                ),
                ("title", models.CharField(blank=True, default="", max_length=120)),
                ("last_message_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by_membership",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="chat_conversations_created",
                        to="establishments.establishmentmembership",
                    ),
                ),
                (
                    "dm_membership_a",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_dm_conversations_a",
                        to="establishments.establishmentmembership",
                    ),
                ),
                (
                    "dm_membership_b",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_dm_conversations_b",
                        to="establishments.establishmentmembership",
                    ),
                ),
                (
                    "establishment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_conversations",
                        to="establishments.establishment",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("body", models.TextField(max_length=2000)),
                ("client_message_id", models.UUIDField()),
                (
                    "author_membership",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="chat_messages_authored",
                        to="establishments.establishmentmembership",
                    ),
                ),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="chat.chatconversation",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at", "id"],
            },
        ),
        migrations.CreateModel(
            name="ChatParticipant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "role",
                    models.CharField(
                        choices=[("member", "Member"), ("admin", "Admin")],
                        default="member",
                        max_length=16,
                    ),
                ),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                ("left_at", models.DateTimeField(blank=True, null=True)),
                ("last_seen_message_id", models.UUIDField(blank=True, null=True)),
                ("last_seen_message_created_at", models.DateTimeField(blank=True, null=True)),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participants",
                        to="chat.chatconversation",
                    ),
                ),
                (
                    "membership",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_participants",
                        to="establishments.establishmentmembership",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="chatconversation",
            index=models.Index(
                fields=["establishment", "-last_message_at"], name="chat_chatco_establi_960dce_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="chatconversation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("dm_membership_a__isnull", False),
                        ("dm_membership_b__isnull", False),
                        ("type", "dm"),
                    ),
                    models.Q(
                        ("dm_membership_a__isnull", True),
                        ("dm_membership_b__isnull", True),
                        ("type", "group"),
                    ),
                    _connector="OR",
                ),
                name="chat_conversation_type_membership_shape",
            ),
        ),
        migrations.AddConstraint(
            model_name="chatconversation",
            constraint=models.UniqueConstraint(
                condition=models.Q(("type", "dm")),
                fields=("establishment", "dm_membership_a", "dm_membership_b"),
                name="uniq_chat_dm_membership_pair",
            ),
        ),
        migrations.AddIndex(
            model_name="chatmessage",
            index=models.Index(
                fields=["conversation", "created_at", "id"], name="chat_chatme_convers_dd99b2_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="chatmessage",
            constraint=models.UniqueConstraint(
                fields=("conversation", "author_membership", "client_message_id"),
                name="uniq_chat_message_client_id",
            ),
        ),
        migrations.AddIndex(
            model_name="chatparticipant",
            index=models.Index(
                fields=["membership", "left_at"], name="chat_chatpa_members_136c1b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chatparticipant",
            index=models.Index(
                fields=["conversation", "left_at"], name="chat_chatpa_convers_a2103d_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="chatparticipant",
            constraint=models.UniqueConstraint(
                fields=("conversation", "membership"), name="uniq_chat_participant_membership"
            ),
        ),
    ]
