# Generated by Django 5.2.14 on 2026-07-17 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        ('establishments', '0027_drop_unique_active_or_invited_director'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatparticipant',
            name='history_cutoff_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatparticipant',
            name='list_hidden_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatparticipant',
            name='pinned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='chatparticipant',
            index=models.Index(fields=['membership', 'list_hidden_at'], name='chat_chatpa_members_ab15af_idx'),
        ),
    ]
