# Generated by Django 5.2.14 on 2026-09-20 11:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0002_participant_pin_hide_cutoff"),
        ("establishments", "0027_drop_unique_active_or_invited_director"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessage",
            name="reply_to_id",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="chatmessage",
            name="body",
            field=models.TextField(blank=True, default="", max_length=2000),
        ),
        migrations.AddIndex(
            model_name="chatmessage",
            index=models.Index(
                fields=["conversation", "reply_to_id"],
                name="chat_chatme_convers_a91c4d_idx",
            ),
        ),
        migrations.CreateModel(
            name="ChatMessageMention",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("start", models.PositiveIntegerField()),
                ("end", models.PositiveIntegerField()),
                (
                    "membership",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_message_mentions",
                        to="establishments.establishmentmembership",
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mentions",
                        to="chat.chatmessage",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="chatmessagemention",
            index=models.Index(
                fields=["message", "start"],
                name="chat_chatme_message_b2e1f0_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="chatmessagemention",
            constraint=models.UniqueConstraint(
                fields=("message", "start"),
                name="uniq_chat_message_mention_start",
            ),
        ),
        migrations.AddConstraint(
            model_name="chatmessagemention",
            constraint=models.CheckConstraint(
                condition=models.Q(("start__lt", models.F("end"))),
                name="chat_message_mention_start_lt_end",
            ),
        ),
    ]
