# Generated by Django 5.2.14 on 2026-09-20 11:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0003_message_reply_mentions"),
        ("establishments", "0027_drop_unique_active_or_invited_director"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatUpload",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("original_filename", models.CharField(max_length=255)),
                ("declared_content_type", models.CharField(max_length=120)),
                ("declared_size_bytes", models.PositiveIntegerField()),
                ("content_type", models.CharField(blank=True, default="", max_length=120)),
                ("size_bytes", models.PositiveIntegerField(blank=True, null=True)),
                ("kind", models.CharField(blank=True, default="", max_length=16)),
                ("storage_key", models.CharField(max_length=512)),
                (
                    "thumbnail_storage_key",
                    models.CharField(blank=True, default="", max_length=512),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("reserved", "Reserved"),
                            ("validated", "Validated"),
                            ("linked", "Linked"),
                            ("expired", "Expired"),
                        ],
                        default="reserved",
                        max_length=20,
                    ),
                ),
                ("expires_at", models.DateTimeField()),
                ("linked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="uploads",
                        to="chat.chatconversation",
                    ),
                ),
                (
                    "establishment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_uploads",
                        to="establishments.establishment",
                    ),
                ),
                (
                    "uploaded_by_membership",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_uploads",
                        to="establishments.establishmentmembership",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="chatupload",
            index=models.Index(
                fields=["conversation", "status", "expires_at"],
                name="chat_chatu_convers_8f1a2c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="chatupload",
            index=models.Index(
                fields=["uploaded_by_membership", "status"],
                name="chat_chatu_uploade_3c91ab_idx",
            ),
        ),
        migrations.CreateModel(
            name="ChatMessageAttachment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("position", models.PositiveSmallIntegerField()),
                ("kind", models.CharField(max_length=16)),
                ("content_type", models.CharField(max_length=120)),
                ("size_bytes", models.PositiveIntegerField()),
                ("original_filename", models.CharField(max_length=255)),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="chat.chatmessage",
                    ),
                ),
                (
                    "upload",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="attachment",
                        to="chat.chatupload",
                    ),
                ),
            ],
            options={"ordering": ["position", "id"]},
        ),
        migrations.AddConstraint(
            model_name="chatmessageattachment",
            constraint=models.UniqueConstraint(
                fields=("message", "position"),
                name="uniq_chat_message_attachment_position",
            ),
        ),
    ]
