# Generated by Django 5.2.14 on 2026-09-21 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0004_chat_uploads_attachments"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatmessageattachment",
            name="upload",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attachment",
                to="chat.chatupload",
            ),
        ),
    ]
