# Generated by Django 5.2.14 on 2026-06-22 14:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('establishments', '0019_drop_orphan_legacy_taxonomy_tables'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_key', models.CharField(choices=[('action.created', 'Action created'), ('action.reassigned', 'Action reassigned'), ('action.pending_validation', 'Action pending validation'), ('action.reopened', 'Action reopened'), ('action.canceled', 'Action canceled'), ('checklist.execution.created', 'Checklist execution created'), ('checklist.execution.canceled', 'Checklist execution canceled'), ('comment.mention.created', 'Comment mention created')], max_length=64)),
                ('subject_type', models.CharField(choices=[('action', 'Action'), ('checklist_execution', 'Checklist execution'), ('comment', 'Comment'), ('signal', 'Signal')], max_length=32)),
                ('subject_id', models.UUIDField()),
                ('priority', models.CharField(choices=[('info', 'Info'), ('action_required', 'Action required'), ('urgent', 'Urgent'), ('system', 'System')], max_length=32)),
                ('status', models.CharField(choices=[('unread', 'Unread'), ('read', 'Read'), ('archived', 'Archived')], default='unread', max_length=16)),
                ('title', models.CharField(max_length=120)),
                ('body', models.CharField(max_length=280)),
                ('dedupe_key', models.CharField(blank=True, default='', max_length=255)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('actor_membership', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='notifications_sent', to='establishments.establishmentmembership')),
                ('establishment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='establishments.establishment')),
                ('recipient_membership', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notifications_received', to='establishments.establishmentmembership')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['establishment', 'recipient_membership', 'status', 'created_at', 'id'], name='notificatio_establi_6b0e62_idx'), models.Index(fields=['recipient_membership', 'status'], name='notificatio_recipie_01d9f4_idx'), models.Index(fields=['recipient_membership', 'dedupe_key', 'created_at'], name='notificatio_recipie_7b09a7_idx')],
            },
        ),
    ]
