# Generated by Django 5.2.14 on 2026-07-03 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_signal_notification_event_keys'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='event_key',
            field=models.CharField(choices=[('action.created', 'Action created'), ('action.reassigned', 'Action reassigned'), ('action.pending_validation', 'Action pending validation'), ('action.reopened', 'Action reopened'), ('action.canceled', 'Action canceled'), ('checklist.execution.created', 'Checklist execution created'), ('checklist.execution.canceled', 'Checklist execution canceled'), ('action_plan.execution.created', 'Action plan execution created'), ('action_plan.execution.pending_validation', 'Action plan execution pending validation'), ('action_plan.execution.canceled', 'Action plan execution canceled'), ('action_plan.execution.reopened', 'Action plan execution reopened'), ('comment.mention.created', 'Comment mention created'), ('signal.created', 'Signal created'), ('signal.urgency_changed', 'Signal urgency changed'), ('signal.pinned', 'Signal pinned'), ('signal.resolved', 'Signal resolved'), ('signal.canceled', 'Signal canceled')], max_length=64),
        ),
        migrations.AlterField(
            model_name='notification',
            name='subject_type',
            field=models.CharField(choices=[('action', 'Action'), ('checklist_execution', 'Checklist execution'), ('action_plan_execution', 'Action plan execution'), ('comment', 'Comment'), ('signal', 'Signal')], max_length=32),
        ),
    ]
