# Generated by Django 5.2.14 on 2026-07-08 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_chat_message_received_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='event_key',
            field=models.CharField(choices=[('action_plan.execution.created', 'Action plan execution created'), ('action_plan.execution.pending_validation', 'Action plan execution pending validation'), ('action_plan.execution.canceled', 'Action plan execution canceled'), ('action_plan.execution.reopened', 'Action plan execution reopened'), ('comment.mention.created', 'Comment mention created'), ('signal.created', 'Signal created'), ('signal.urgency_changed', 'Signal urgency changed'), ('signal.pinned', 'Signal pinned'), ('signal.resolved', 'Signal resolved'), ('signal.canceled', 'Signal canceled'), ('chat.message.received', 'Chat message received')], max_length=64),
        ),
    ]
