# Generated by Django 5.2.14 on 2026-07-11 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establishments', '0021_establishmentmembership_push_enabled'),
        ('notifications', '0012_remove_signal_urgency_changed_event_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='idempotency_key',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key__gt', '')), fields=('recipient_membership', 'idempotency_key'), name='notifications_recipient_idempotency_key_uniq'),
        ),
    ]
