# Generated by Codex on 2026-07-31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0016_signal_resolution_request"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="event_key",
            field=models.CharField(
                choices=[
                    (
                        "action_plan.execution.created",
                        "Action plan execution created",
                    ),
                    (
                        "action_plan.execution.created_from_signal",
                        "Action plan execution created from signal",
                    ),
                    (
                        "action_plan.execution.pending_validation",
                        "Action plan execution pending validation",
                    ),
                    (
                        "action_plan.execution.canceled",
                        "Action plan execution canceled",
                    ),
                    (
                        "action_plan.execution.reopened",
                        "Action plan execution reopened",
                    ),
                    (
                        "action_plan.execution.started",
                        "Action plan execution started",
                    ),
                    (
                        "action_plan.execution.done",
                        "Action plan execution done",
                    ),
                    (
                        "action_plan.execution.validated",
                        "Action plan execution validated",
                    ),
                    (
                        "action_plan.execution.updated",
                        "Action plan execution updated",
                    ),
                    ("comment.mention.created", "Comment mention created"),
                    ("comment.signal.created", "Comment signal created"),
                    (
                        "comment.action_plan_execution.created",
                        "Comment action plan execution created",
                    ),
                    ("comment.reply.created", "Comment reply created"),
                    ("signal.created", "Signal created"),
                    (
                        "signal.created.unassigned_global",
                        "Signal created unassigned global",
                    ),
                    ("signal.pinned", "Signal pinned"),
                    ("signal.resolved", "Signal resolved"),
                    ("signal.canceled", "Signal canceled"),
                    (
                        "signal.resolution_request.created",
                        "Signal resolution request created",
                    ),
                    (
                        "signal.resolution_request.approved",
                        "Signal resolution request approved",
                    ),
                    (
                        "signal.resolution_request.rejected",
                        "Signal resolution request rejected",
                    ),
                    (
                        "signal.resolution_request.canceled",
                        "Signal resolution request canceled",
                    ),
                    ("chat.message.received", "Chat message received"),
                ],
                max_length=64,
            ),
        ),
    ]
