from django.urls import path

from houston.checklists.api.views import (
    ChecklistAssignmentCreateView,
    ChecklistAssignmentDeactivateView,
    ChecklistAssignmentDetailView,
    ChecklistAssignmentListView,
    ChecklistExecutionCancelView,
    ChecklistExecutionDetailView,
    ChecklistTaskExecutionCreateObservationView,
    ChecklistTaskExecutionMarkDoneView,
    ChecklistTaskExecutionSkipView,
    ChecklistTaskTemplateCreateView,
    ChecklistTaskTemplateDetailView,
    ChecklistTaskTemplateReorderView,
    ChecklistTemplateActivateView,
    ChecklistTemplateDeactivateView,
    ChecklistTemplateDetailView,
    ChecklistTemplateExecutionCreateView,
    ChecklistTemplateListCreateView,
    ChecklistTemplateScheduleView,
)

urlpatterns = [
    path(
        "establishments/<uuid:establishment_id>/checklist-templates/",
        ChecklistTemplateListCreateView.as_view(),
        name="checklist-template-list-create",
    ),
    path(
        "establishments/<uuid:establishment_id>/checklist-templates/<uuid:template_id>/",
        ChecklistTemplateDetailView.as_view(),
        name="checklist-template-detail",
    ),
    path(
        "establishments/<uuid:establishment_id>/checklist-templates/<uuid:template_id>/activate/",
        ChecklistTemplateActivateView.as_view(),
        name="checklist-template-activate",
    ),
    path(
        "establishments/<uuid:establishment_id>/checklist-templates/<uuid:template_id>/deactivate/",
        ChecklistTemplateDeactivateView.as_view(),
        name="checklist-template-deactivate",
    ),
    path(
        "establishments/<uuid:establishment_id>/checklist-templates/<uuid:template_id>/tasks/",
        ChecklistTaskTemplateCreateView.as_view(),
        name="checklist-task-template-create",
    ),
    path(
        "establishments/<uuid:establishment_id>/checklist-templates/<uuid:template_id>/tasks/reorder/",
        ChecklistTaskTemplateReorderView.as_view(),
        name="checklist-task-template-reorder",
    ),
    path(
        "establishments/<uuid:establishment_id>/checklist-task-templates/<uuid:task_template_id>/",
        ChecklistTaskTemplateDetailView.as_view(),
        name="checklist-task-template-detail",
    ),
    path(
        "establishments/<uuid:establishment_id>/checklist-assignments/",
        ChecklistAssignmentListView.as_view(),
        name="checklist-assignment-list",
    ),
    path(
        "establishments/<uuid:establishment_id>/checklist-templates/<uuid:template_id>/assignments/",
        ChecklistAssignmentCreateView.as_view(),
        name="checklist-assignment-create",
    ),
    path(
        "establishments/<uuid:establishment_id>/checklist-assignments/<uuid:assignment_id>/",
        ChecklistAssignmentDetailView.as_view(),
        name="checklist-assignment-detail",
    ),
    path(
        "establishments/<uuid:establishment_id>/checklist-assignments/<uuid:assignment_id>/deactivate/",
        ChecklistAssignmentDeactivateView.as_view(),
        name="checklist-assignment-deactivate",
    ),
    path(
        "establishments/<uuid:establishment_id>/checklist-templates/<uuid:template_id>/schedule/",
        ChecklistTemplateScheduleView.as_view(),
        name="checklist-template-schedule",
    ),
    path(
        "establishments/<uuid:establishment_id>/checklist-templates/<uuid:template_id>/executions/",
        ChecklistTemplateExecutionCreateView.as_view(),
        name="checklist-template-execution-create",
    ),
    path(
        "establishments/<uuid:establishment_id>/checklist-executions/<uuid:execution_id>/",
        ChecklistExecutionDetailView.as_view(),
        name="checklist-execution-detail",
    ),
    path(
        "establishments/<uuid:establishment_id>/checklist-executions/<uuid:execution_id>/cancel/",
        ChecklistExecutionCancelView.as_view(),
        name="checklist-execution-cancel",
    ),
    path(
        "establishments/<uuid:establishment_id>/checklist-task-executions/<uuid:task_execution_id>/mark-done/",
        ChecklistTaskExecutionMarkDoneView.as_view(),
        name="checklist-task-execution-mark-done",
    ),
    path(
        "establishments/<uuid:establishment_id>/checklist-task-executions/<uuid:task_execution_id>/skip/",
        ChecklistTaskExecutionSkipView.as_view(),
        name="checklist-task-execution-skip",
    ),
    path(
        "establishments/<uuid:establishment_id>/checklist-task-executions/<uuid:task_execution_id>/create-observation/",
        ChecklistTaskExecutionCreateObservationView.as_view(),
        name="checklist-task-execution-create-observation",
    ),
]
