# Generated by Django 5.2.14 on 2026-06-03 21:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('establishments', '0012_remove_membership_domain'),
        ('signals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('instruction', models.TextField(max_length=2000)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In progress'), ('pending_validation', 'Pending validation'), ('reopened', 'Reopened'), ('done', 'Done'), ('canceled', 'Canceled')], default='open', max_length=32)),
                ('due_at', models.DateTimeField()),
                ('last_activity_at', models.DateTimeField()),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('marked_done_at', models.DateTimeField(blank=True, null=True)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='actions_assigned', to='establishments.establishmentmembership')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='actions_created', to='establishments.establishmentmembership')),
                ('establishment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='establishments.establishment')),
                ('operational_domain', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='actions', to='establishments.operationaldomain')),
                ('operational_module', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='actions', to='establishments.operationalmodule')),
                ('operational_subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='actions', to='establishments.operationalsubject')),
                ('signal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='actions', to='signals.signal')),
            ],
            options={
                'indexes': [models.Index(fields=['establishment', 'status', 'due_at', 'last_activity_at'], name='action_exec_feed_sort_idx'), models.Index(fields=['signal', 'status'], name='action_signal_status_idx'), models.Index(fields=['establishment', 'assigned_to'], name='action_est_assignee_idx'), models.Index(fields=['establishment', 'created_by'], name='action_est_creator_idx')],
            },
        ),
    ]
