# Generated by Django 5.2.14 on 2026-06-07 14:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("actions", "0003_action_affected_business_unit"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="action",
            name="operational_domain",
        ),
        migrations.RemoveField(
            model_name="action",
            name="operational_module",
        ),
        migrations.RemoveField(
            model_name="action",
            name="operational_subject",
        ),
    ]
