# Generated by Django 5.2.14 on 2026-06-18 10:56

import uuid

import django.db.models.deletion
from django.db import migrations, models


def copy_assigned_to_assignees(apps, schema_editor):
    Action = apps.get_model("actions", "Action")
    ActionAssignee = apps.get_model("actions", "ActionAssignee")
    in_progress = "in_progress"
    for action in Action.objects.exclude(assigned_to_id__isnull=True).iterator():
        ActionAssignee.objects.create(
            id=uuid.uuid4(),
            action_id=action.id,
            membership_id=action.assigned_to_id,
        )
        if action.status == in_progress:
            action.accepted_by_id = action.assigned_to_id
            action.save(update_fields=["accepted_by_id"])


class Migration(migrations.Migration):

    dependencies = [
        ("actions", "0004_remove_legacy_operational_taxonomy_fks"),
        ("establishments", "0019_drop_orphan_legacy_taxonomy_tables"),
    ]

    operations = [
        migrations.AddField(
            model_name="action",
            name="accepted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="actions_accepted",
                to="establishments.establishmentmembership",
            ),
        ),
        migrations.AddField(
            model_name="action",
            name="requires_validation",
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name="ActionAssignee",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "action",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignee_links",
                        to="actions.action",
                    ),
                ),
                (
                    "membership",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="action_assignments",
                        to="establishments.establishmentmembership",
                    ),
                ),
            ],
        ),
        migrations.RunPython(copy_assigned_to_assignees, migrations.RunPython.noop),
        migrations.RemoveIndex(
            model_name="action",
            name="action_est_assignee_idx",
        ),
        migrations.RemoveField(
            model_name="action",
            name="assigned_to",
        ),
        migrations.AddIndex(
            model_name="actionassignee",
            index=models.Index(
                fields=["membership", "action"],
                name="action_assignee_member_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="actionassignee",
            constraint=models.UniqueConstraint(
                fields=("action", "membership"),
                name="action_assignee_unique",
            ),
        ),
    ]
