# Generated by Django 5.2.14 on 2026-06-08 15:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("establishments", "0016_drop_legacy_taxonomy"),
        ("observations", "0003_observationprocessing_attempt_count_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChecklistAssignment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("start_at", models.DateTimeField()),
                ("due_at", models.DateTimeField()),
                ("recurrence_days", models.JSONField(blank=True, default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("inactive", "Inactive")],
                        default="active",
                        max_length=16,
                    ),
                ),
                ("last_materialized_at", models.DateTimeField(blank=True, null=True)),
                (
                    "assigned_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="checklist_assignments_created",
                        to="establishments.establishmentmembership",
                    ),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="checklist_assignments_received",
                        to="establishments.establishmentmembership",
                    ),
                ),
                (
                    "business_unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="checklist_assignments",
                        to="establishments.businessunit",
                    ),
                ),
                (
                    "establishment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checklist_assignments",
                        to="establishments.establishment",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ChecklistTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "checklist_type",
                    models.CharField(
                        choices=[("shared", "Shared"), ("personal", "Personal")], max_length=16
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, default="", max_length=2000)),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("inactive", "Inactive")],
                        default="inactive",
                        max_length=16,
                    ),
                ),
                (
                    "business_unit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="checklist_templates",
                        to="establishments.businessunit",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="checklist_templates_created",
                        to="establishments.establishmentmembership",
                    ),
                ),
                (
                    "establishment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checklist_templates",
                        to="establishments.establishment",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ChecklistTaskTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=200)),
                ("instructions", models.TextField(blank=True, default="", max_length=2000)),
                ("position", models.PositiveIntegerField()),
                (
                    "checklist_template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="task_templates",
                        to="checklists.checklisttemplate",
                    ),
                ),
            ],
            options={
                "ordering": ["position", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="ChecklistExecution",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "checklist_type",
                    models.CharField(
                        choices=[("shared", "Shared"), ("personal", "Personal")], max_length=16
                    ),
                ),
                ("template_title", models.CharField(max_length=200)),
                ("template_description", models.TextField(blank=True, default="", max_length=2000)),
                ("start_at", models.DateTimeField(blank=True, null=True)),
                ("visible_from", models.DateTimeField(blank=True, null=True)),
                ("due_at", models.DateTimeField(blank=True, null=True)),
                ("occurrence_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("assigned", "Assigned"),
                            ("in_progress", "In progress"),
                            ("done", "Done"),
                            ("canceled", "Canceled"),
                        ],
                        default="assigned",
                        max_length=16,
                    ),
                ),
                ("last_activity_at", models.DateTimeField()),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("done_at", models.DateTimeField(blank=True, null=True)),
                ("canceled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "assigned_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="checklist_executions_assigned_by",
                        to="establishments.establishmentmembership",
                    ),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="checklist_executions_assigned",
                        to="establishments.establishmentmembership",
                    ),
                ),
                (
                    "business_unit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="checklist_executions",
                        to="establishments.businessunit",
                    ),
                ),
                (
                    "checklist_assignment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="executions",
                        to="checklists.checklistassignment",
                    ),
                ),
                (
                    "establishment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checklist_executions",
                        to="establishments.establishment",
                    ),
                ),
                (
                    "checklist_template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="executions",
                        to="checklists.checklisttemplate",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="checklistassignment",
            name="checklist_template",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assignments",
                to="checklists.checklisttemplate",
            ),
        ),
        migrations.CreateModel(
            name="ChecklistTaskExecution",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=200)),
                ("instructions", models.TextField(blank=True, default="", max_length=2000)),
                ("position", models.PositiveIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("done", "Done"),
                            ("skipped", "Skipped"),
                            ("observation_created", "Observation created"),
                        ],
                        default="pending",
                        max_length=32,
                    ),
                ),
                ("skipped_reason", models.CharField(blank=True, max_length=500, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("skipped_at", models.DateTimeField(blank=True, null=True)),
                ("observation_created_at", models.DateTimeField(blank=True, null=True)),
                (
                    "checklist_execution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="task_executions",
                        to="checklists.checklistexecution",
                    ),
                ),
                (
                    "observation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="checklist_task_executions",
                        to="observations.observation",
                    ),
                ),
                (
                    "checklist_task_template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="task_executions",
                        to="checklists.checklisttasktemplate",
                    ),
                ),
            ],
            options={
                "ordering": ["position", "created_at"],
                "indexes": [
                    models.Index(
                        fields=["checklist_execution", "position"],
                        name="checklists__checkli_70f62b_idx",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="checklisttemplate",
            index=models.Index(
                fields=["establishment", "checklist_type", "status"],
                name="checklists__establi_600fb9_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="checklisttemplate",
            index=models.Index(
                fields=["establishment", "created_by", "checklist_type"],
                name="checklists__establi_443222_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="checklisttemplate",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("business_unit__isnull", False), ("checklist_type", "shared")),
                    models.Q(("business_unit__isnull", True), ("checklist_type", "personal")),
                    _connector="OR",
                ),
                name="checklist_template_business_unit_by_type",
            ),
        ),
        migrations.AddIndex(
            model_name="checklisttasktemplate",
            index=models.Index(
                fields=["checklist_template", "position"], name="checklists__checkli_a53b44_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="checklisttasktemplate",
            constraint=models.UniqueConstraint(
                fields=("checklist_template", "position"),
                name="uniq_checklist_task_template_position",
            ),
        ),
        migrations.AddIndex(
            model_name="checklistexecution",
            index=models.Index(
                fields=["establishment", "status", "visible_from", "last_activity_at"],
                name="checklist_exec_feed_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="checklistexecution",
            index=models.Index(
                fields=["assigned_to", "status"], name="checklists__assigne_5a76d6_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="checklistexecution",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("business_unit__isnull", False),
                        ("checklist_assignment__isnull", False),
                        ("checklist_type", "shared"),
                    ),
                    models.Q(
                        ("business_unit__isnull", True),
                        ("checklist_assignment__isnull", True),
                        ("checklist_type", "personal"),
                    ),
                    _connector="OR",
                ),
                name="checklist_execution_type_shape",
            ),
        ),
        migrations.AddConstraint(
            model_name="checklistexecution",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("checklist_type", "personal"), ("due_at__isnull", True)),
                    ("checklist_type", "shared"),
                    _connector="OR",
                ),
                name="checklist_execution_personal_no_due_at",
            ),
        ),
        migrations.AddConstraint(
            model_name="checklistexecution",
            constraint=models.UniqueConstraint(
                condition=models.Q(("checklist_assignment__isnull", False)),
                fields=("checklist_assignment", "occurrence_date"),
                name="uniq_checklist_execution_assignment_occurrence",
            ),
        ),
        migrations.AddConstraint(
            model_name="checklistexecution",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("checklist_type", "personal"), ("status__in", ["assigned", "in_progress"])
                ),
                fields=("checklist_template",),
                name="uniq_active_personal_execution_per_template",
            ),
        ),
        migrations.AddIndex(
            model_name="checklistassignment",
            index=models.Index(
                fields=["establishment", "status"], name="checklists__establi_3ec89c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="checklistassignment",
            index=models.Index(
                fields=["assigned_to", "status"], name="checklists__assigne_0b191f_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="checklistassignment",
            constraint=models.CheckConstraint(
                condition=models.Q(("due_at__gt", models.F("start_at"))),
                name="checklist_assignment_due_after_start",
            ),
        ),
    ]
