# Generated by Django 5.2.14 on 2026-06-09 21:40

from django.db import migrations, models

CHECKLIST_TYPE_PERSONAL = "personal"
CHECKLIST_TYPE_SHARED = "shared"
CHECKLIST_BADGE_PROCESS = "process"
EXECUTION_SOURCE_ASSIGNMENT = "assignment"
EXECUTION_SOURCE_TEMPLATE = "template"


def purge_personal_and_tag_shared(apps, schema_editor):
    ChecklistTemplate = apps.get_model("checklists", "ChecklistTemplate")
    ChecklistExecution = apps.get_model("checklists", "ChecklistExecution")
    ChecklistTaskExecution = apps.get_model("checklists", "ChecklistTaskExecution")
    Observation = apps.get_model("observations", "Observation")

    personal_execution_ids = list(
        ChecklistExecution.objects.filter(checklist_type=CHECKLIST_TYPE_PERSONAL).values_list(
            "id",
            flat=True,
        )
    )
    if personal_execution_ids:
        personal_task_execution_ids = list(
            ChecklistTaskExecution.objects.filter(
                checklist_execution_id__in=personal_execution_ids,
            ).values_list("id", flat=True)
        )
        if personal_task_execution_ids:
            Observation.objects.filter(
                checklist_task_execution_id__in=personal_task_execution_ids,
            ).update(checklist_task_execution_id=None)
        Observation.objects.filter(
            checklist_execution_id__in=personal_execution_ids,
        ).update(checklist_execution_id=None)
        ChecklistExecution.objects.filter(id__in=personal_execution_ids).delete()

    ChecklistTemplate.objects.filter(checklist_type=CHECKLIST_TYPE_PERSONAL).delete()

    ChecklistTemplate.objects.filter(checklist_type=CHECKLIST_TYPE_SHARED).update(
        badge=CHECKLIST_BADGE_PROCESS,
    )
    ChecklistExecution.objects.filter(
        checklist_type=CHECKLIST_TYPE_SHARED,
        checklist_assignment_id__isnull=False,
    ).update(execution_source=EXECUTION_SOURCE_ASSIGNMENT)
    ChecklistExecution.objects.filter(
        checklist_type=CHECKLIST_TYPE_SHARED,
        checklist_assignment_id__isnull=True,
    ).update(execution_source=EXECUTION_SOURCE_TEMPLATE)


class Migration(migrations.Migration):
    dependencies = [
        ("checklists", "0005_assignment_schedule_period"),
        ("establishments", "0018_establishment_chat_enabled"),
        ("observations", "0004_observation_checklist_origin"),
    ]

    operations = [
        migrations.AddField(
            model_name="checklistexecution",
            name="execution_source",
            field=models.CharField(
                choices=[
                    ("flash_todo", "Flash to-do"),
                    ("template", "Template"),
                    ("assignment", "Assignment"),
                ],
                default="template",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="checklisttemplate",
            name="badge",
            field=models.CharField(
                choices=[("process", "Process"), ("todo", "To-do")],
                default="todo",
                max_length=16,
            ),
        ),
        migrations.AddIndex(
            model_name="checklisttemplate",
            index=models.Index(
                fields=["establishment", "badge", "status"],
                name="checklists__establi_3fd9c0_idx",
            ),
        ),
        migrations.RunPython(purge_personal_and_tag_shared, migrations.RunPython.noop),
    ]
