# Generated by Django 5.2.14 on 2026-06-09 22:00

from django.db import migrations, models


def backfill_execution_business_units(apps, schema_editor):
    ChecklistExecution = apps.get_model("checklists", "ChecklistExecution")
    for execution in ChecklistExecution.objects.filter(business_unit_id__isnull=True).iterator():
        template = execution.checklist_template
        if template is not None and template.business_unit_id is not None:
            execution.business_unit_id = template.business_unit_id
            execution.save(update_fields=["business_unit_id"])
            continue
        assignment = execution.checklist_assignment
        if assignment is not None and assignment.business_unit_id is not None:
            execution.business_unit_id = assignment.business_unit_id
            execution.save(update_fields=["business_unit_id"])


class Migration(migrations.Migration):
    dependencies = [
        ("checklists", "0006_add_badge_execution_source_purge_personal"),
        ("establishments", "0018_establishment_chat_enabled"),
    ]

    operations = [
        migrations.RunPython(backfill_execution_business_units, migrations.RunPython.noop),
        migrations.RemoveConstraint(
            model_name="checklisttemplate",
            name="checklist_template_business_unit_by_type",
        ),
        migrations.RemoveConstraint(
            model_name="checklistexecution",
            name="checklist_execution_type_shape",
        ),
        migrations.RemoveConstraint(
            model_name="checklistexecution",
            name="checklist_execution_personal_no_end_at",
        ),
        migrations.RemoveConstraint(
            model_name="checklistexecution",
            name="uniq_active_personal_execution_per_template",
        ),
        migrations.RemoveIndex(
            model_name="checklisttemplate",
            name="checklists__establi_600fb9_idx",
        ),
        migrations.RemoveIndex(
            model_name="checklisttemplate",
            name="checklists__establi_443222_idx",
        ),
        migrations.RemoveField(
            model_name="checklisttemplate",
            name="checklist_type",
        ),
        migrations.RemoveField(
            model_name="checklistexecution",
            name="checklist_type",
        ),
        migrations.AlterField(
            model_name="checklisttemplate",
            name="business_unit",
            field=models.ForeignKey(
                on_delete=models.PROTECT,
                related_name="checklist_templates",
                to="establishments.businessunit",
            ),
        ),
        migrations.AlterField(
            model_name="checklistexecution",
            name="business_unit",
            field=models.ForeignKey(
                on_delete=models.PROTECT,
                related_name="checklist_executions",
                to="establishments.businessunit",
            ),
        ),
        migrations.AddIndex(
            model_name="checklisttemplate",
            index=models.Index(
                fields=["establishment", "created_by"],
                name="checklists__establi_8f0a62_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="checklisttemplate",
            constraint=models.CheckConstraint(
                condition=models.Q(("business_unit__isnull", False)),
                name="checklist_template_business_unit_required",
            ),
        ),
        migrations.AddConstraint(
            model_name="checklistexecution",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("business_unit__isnull", False),
                        ("checklist_assignment__isnull", False),
                        ("execution_source", "assignment"),
                    ),
                    models.Q(
                        ("business_unit__isnull", False),
                        ("checklist_assignment__isnull", True),
                        ("checklist_template__isnull", False),
                        ("execution_source", "template"),
                    ),
                    models.Q(
                        ("business_unit__isnull", False),
                        ("checklist_assignment__isnull", True),
                        ("checklist_template__isnull", True),
                        ("execution_source", "flash_todo"),
                    ),
                    _connector="OR",
                ),
                name="checklist_execution_source_shape",
            ),
        ),
    ]
