# Generated by Django 5.2.14 on 2026-06-09 21:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("checklists", "0007_remove_checklist_type_finalize_constraints"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="checklisttemplate",
            new_name="checklists__establi_ce34e7_idx",
            old_name="checklists__establi_8f0a62_idx",
        ),
    ]
