# Generated by Django 5.2.14 on 2026-06-09 21:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("checklists", "0008_rename_template_created_by_index"),
        ("establishments", "0018_establishment_chat_enabled"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="checklistexecution",
            name="checklist_execution_source_shape",
        ),
        migrations.AddConstraint(
            model_name="checklistexecution",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("business_unit__isnull", False),
                        ("checklist_assignment__isnull", False),
                        ("execution_source", "assignment"),
                    ),
                    models.Q(
                        ("business_unit__isnull", False),
                        ("checklist_assignment__isnull", True),
                        ("checklist_template__isnull", False),
                        ("execution_source", "template"),
                    ),
                    models.Q(
                        ("business_unit__isnull", False),
                        ("checklist_assignment__isnull", True),
                        ("checklist_template__isnull", True),
                        ("execution_source", "template"),
                        ("status__in", frozenset(["canceled", "done"])),
                    ),
                    models.Q(
                        ("business_unit__isnull", False),
                        ("checklist_assignment__isnull", True),
                        ("checklist_template__isnull", True),
                        ("execution_source", "flash_todo"),
                    ),
                    _connector="OR",
                ),
                name="checklist_execution_source_shape",
            ),
        ),
    ]
