# Generated by Django 5.2.14 on 2026-06-16 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0011_remove_checklist_badge'),
        ('establishments', '0019_drop_orphan_legacy_taxonomy_tables'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='checklistexecution',
            name='checklist_execution_source_shape',
        ),
        migrations.AddConstraint(
            model_name='checklistexecution',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('business_unit__isnull', False), ('checklist_assignment__isnull', False), ('execution_source', 'assignment')), models.Q(('business_unit__isnull', False), ('checklist_assignment__isnull', True), ('checklist_template__isnull', False), ('execution_source', 'template')), models.Q(('business_unit__isnull', False), ('checklist_assignment__isnull', True), ('checklist_template__isnull', True), ('execution_source', 'template'), ('status__in', frozenset(['canceled', 'done']))), _connector='OR'), name='checklist_execution_source_shape'),
        ),
    ]
