from django.urls import path

from houston.action_plans.api.views import (
    ActionPlanActivateView,
    ActionPlanDeactivateView,
    ActionPlanDetailView,
    ActionPlanExecutionCancelView,
    ActionPlanExecutionDetailView,
    ActionPlanExecutionMarkDoneView,
    ActionPlanExecutionReopenView,
    ActionPlanExecutionTaskCreateObservationView,
    ActionPlanExecutionTaskMarkDoneView,
    ActionPlanExecutionTaskSkipView,
    ActionPlanExecutionValidateView,
    ActionPlanListCreateView,
    ActionPlanUseView,
)

urlpatterns = [
    path(
        "establishments/<uuid:establishment_id>/action-plans/",
        ActionPlanListCreateView.as_view(),
        name="action-plan-list-create",
    ),
    path(
        "establishments/<uuid:establishment_id>/action-plans/<uuid:action_plan_id>/",
        ActionPlanDetailView.as_view(),
        name="action-plan-detail",
    ),
    path(
        "establishments/<uuid:establishment_id>/action-plans/<uuid:action_plan_id>/activate/",
        ActionPlanActivateView.as_view(),
        name="action-plan-activate",
    ),
    path(
        "establishments/<uuid:establishment_id>/action-plans/<uuid:action_plan_id>/deactivate/",
        ActionPlanDeactivateView.as_view(),
        name="action-plan-deactivate",
    ),
    path(
        "establishments/<uuid:establishment_id>/action-plans/<uuid:action_plan_id>/use/",
        ActionPlanUseView.as_view(),
        name="action-plan-use",
    ),
    path(
        "establishments/<uuid:establishment_id>/action-plan-executions/<uuid:execution_id>/",
        ActionPlanExecutionDetailView.as_view(),
        name="action-plan-execution-detail",
    ),
    path(
        "establishments/<uuid:establishment_id>/action-plan-executions/<uuid:execution_id>/mark-done/",
        ActionPlanExecutionMarkDoneView.as_view(),
        name="action-plan-execution-mark-done",
    ),
    path(
        "establishments/<uuid:establishment_id>/action-plan-executions/<uuid:execution_id>/validate/",
        ActionPlanExecutionValidateView.as_view(),
        name="action-plan-execution-validate",
    ),
    path(
        "establishments/<uuid:establishment_id>/action-plan-executions/<uuid:execution_id>/reopen/",
        ActionPlanExecutionReopenView.as_view(),
        name="action-plan-execution-reopen",
    ),
    path(
        "establishments/<uuid:establishment_id>/action-plan-executions/<uuid:execution_id>/cancel/",
        ActionPlanExecutionCancelView.as_view(),
        name="action-plan-execution-cancel",
    ),
    path(
        (
            "establishments/<uuid:establishment_id>/action-plan-execution-tasks/"
            "<uuid:task_execution_id>/mark-done/"
        ),
        ActionPlanExecutionTaskMarkDoneView.as_view(),
        name="action-plan-execution-task-mark-done",
    ),
    path(
        (
            "establishments/<uuid:establishment_id>/action-plan-execution-tasks/"
            "<uuid:task_execution_id>/skip/"
        ),
        ActionPlanExecutionTaskSkipView.as_view(),
        name="action-plan-execution-task-skip",
    ),
    path(
        (
            "establishments/<uuid:establishment_id>/action-plan-execution-tasks/"
            "<uuid:task_execution_id>/create-observation/"
        ),
        ActionPlanExecutionTaskCreateObservationView.as_view(),
        name="action-plan-execution-task-create-observation",
    ),
]
